"""MCP ops tools for Haxaml."""

from haxaml.mcp.base import *
from haxaml.setup.service import apply_setup, setup_data
from haxaml.versioning import upgrade_specs


@mcp_app.tool()
def haxaml_export(
    agent: str = "generic",
    project_dir: str = ".",
    target: Optional[str] = None,
    dry_run: bool = False,
    diff_preview: bool = False,
    override_native: bool = False,
    overwrite_existing: bool = False,
    detail: str = DETAIL_SHORT,
) -> dict:
    """Export FRAME to an agent-native markdown file.

    Default export writes HAXAML.md. Explicit agent exports can generate
    CLAUDE.md, haxaml-agents.md, .cursor/rules/haxaml.mdc, etc.
    Use agent='all' to export for all supported agents.

    Supported agents: claude, codex, cursor, windsurf, copilot, gemini, generic
    """
    detail_mode, detail_err = _normalize_detail("haxaml_export", detail)
    if detail_err:
        return detail_err

    target_path = (target or "").strip() or None

    if agent == "all":
        if target_path is not None:
            return _err(
                "haxaml_export",
                "invalid_target_with_all",
                "target cannot be used with agent='all'.",
            )
        if dry_run:
            return _err(
                "haxaml_export",
                "invalid_dry_run_with_all",
                "dry_run is only supported with a single agent.",
            )
        lines = []
        exported = []
        # Multi-agent export intentionally writes one canonical file per agent;
        # we do not try to merge them into a shared target path.
        for a in list_agents():
            path = export_to_file(
                project_dir,
                a["name"],
                override_native=override_native,
                overwrite_existing=overwrite_existing,
            )
            lines.append(f"✓ {a['name']:10s} → {path}")
            exported.append({"agent": a["name"], "path": path})
        return _ok(
            "haxaml_export",
            {"message": "\n".join(lines), "exports": exported},
            detail=detail_mode,
        )

    if agent not in AGENT_CONFIGS:
        available = ", ".join(a["name"] for a in list_agents())
        return _err(
            "haxaml_export",
            "unknown_agent",
            f"Unknown agent '{agent}'. Available: {available}",
        )

    resolved_target = _resolve_export_target(
        project_dir=project_dir,
        agent=agent,
        target=target_path,
        override_native=override_native,
    )
    content = export_frame_to_markdown(project_dir, agent)

    existing = ""
    exists = resolved_target.exists()
    if exists:
        existing = resolved_target.read_text(encoding="utf-8", errors="ignore")

    diff = ""
    summary = {"changed": not exists or existing != content, "added_lines": 0, "removed_lines": 0}
    if diff_preview:
        diff = _build_unified_diff(existing, content, resolved_target)
        summary = _diff_summary(diff)

    if dry_run:
        message = f"✓ Dry run complete for {resolved_target}"
        return _ok(
            "haxaml_export",
            {
                "message": message,
                "agent": agent,
                "would_write": True,
                "target_path": str(resolved_target),
                "exists": exists,
                "generated_marker_present": ("Generated by Haxaml from FRAME" in existing) if exists else False,
                "diff": diff,
                "summary": summary,
            },
            detail=detail_mode,
        )

    try:
        path = export_to_file(
            project_dir,
            agent,
            output_path=target_path,
            override_native=override_native,
            overwrite_existing=overwrite_existing,
        )
        message = f"✓ Exported to {path}"
        return _ok(
            "haxaml_export",
            {
                "message": message,
                "agent": agent,
                "target_path": path,
                "exists": exists,
                "generated_marker_present": ("Generated by Haxaml from FRAME" in existing) if exists else False,
                "diff": diff if diff_preview else "",
                "summary": summary if diff_preview else {"changed": True, "added_lines": 0, "removed_lines": 0},
            },
            detail=detail_mode,
        )
    except FileExistsError as e:
        return _err("haxaml_export", "protected_existing_file", str(e))


@mcp_app.tool()
def haxaml_upgrade(
    target_version: Optional[str] = None,
    include_mcp: bool = True,
    include_ui: bool = False,
    dry_run: bool = False,
    detail: str = DETAIL_SHORT,
) -> dict:
    """Upgrade haxaml and optional companion packages using uv tool management."""
    detail_mode, detail_err = _normalize_detail("haxaml_upgrade", detail)
    if detail_err:
        return detail_err

    if not shutil.which("uv"):
        return _err(
            "haxaml_upgrade",
            "uv_not_found",
            "uv is required for upgrade. Install uv first: https://docs.astral.sh/uv/",
        )

    specs = upgrade_specs(
        target_version=target_version,
        include_mcp=include_mcp,
        include_ui=include_ui,
    )

    upgrade_cmd = ["uv", "tool", "upgrade", *specs]
    if dry_run:
        return _ok(
            "haxaml_upgrade",
            {
                "message": "✓ Dry run upgrade plan prepared.",
                "command": upgrade_cmd,
                "target_version": target_version or "latest",
                "include_mcp": include_mcp,
                "include_ui": include_ui,
            },
            detail=detail_mode,
        )

    primary = subprocess.run(upgrade_cmd, capture_output=True, text=True)
    if primary.returncode == 0:
        return _ok(
            "haxaml_upgrade",
            {
                "message": "✓ Upgrade complete via `uv tool upgrade`.",
                "command": upgrade_cmd,
                "stdout": (primary.stdout or "").strip(),
                "stderr": (primary.stderr or "").strip(),
                "include_mcp": include_mcp,
                "include_ui": include_ui,
                "target_version": target_version or "latest",
            },
            detail=detail_mode,
        )

    # Older uv versions or partial tool installs can make the bulk upgrade fail
    # even though per-package upgrade/install still works, so we fall back to
    # one spec at a time before declaring the operation failed.
    failures = []
    executed = []
    for spec in specs:
        cmd = ["uv", "tool", "install", "--upgrade", spec]
        step = subprocess.run(cmd, capture_output=True, text=True)
        executed.append({"command": cmd, "returncode": step.returncode})
        if step.returncode != 0:
            failures.append(
                {
                    "spec": spec,
                    "stderr": (step.stderr or "").strip(),
                    "stdout": (step.stdout or "").strip(),
                }
            )

    if failures:
        return _err(
            "haxaml_upgrade",
            "upgrade_failed",
            "Upgrade failed for one or more packages.",
            {
                "command": upgrade_cmd,
                "primary_stderr": (primary.stderr or "").strip(),
                "primary_stdout": (primary.stdout or "").strip(),
                "failures": failures,
                "executed": executed,
            },
        )

    return _ok(
        "haxaml_upgrade",
        {
            "message": "✓ Upgrade complete via fallback install flow.",
            "command": upgrade_cmd,
            "include_mcp": include_mcp,
            "include_ui": include_ui,
            "target_version": target_version or "latest",
            "executed": executed,
        },
        detail=detail_mode,
    )


@mcp_app.tool()
def haxaml_setup(
    project_dir: str = ".",
    scope: str = "project",
    target: str = "auto",
    mode: str = "auto",
    only: Optional[list[str]] = None,
    with_workflow: bool = False,
    force: bool = False,
    detail: str = DETAIL_SHORT,
) -> dict:
    """Install Haxaml onboarding into project or user-native agent surfaces."""
    detail_mode, detail_err = _normalize_detail("haxaml_setup", detail)
    if detail_err:
        return detail_err

    try:
        plan, apply_result = apply_setup(
            project_dir=project_dir,
            scope=scope,
            target=target,
            mode=mode,
            only=only,
            with_workflow=with_workflow,
            force=force,
        )
    except (KeyError, ValueError) as exc:
        return _err("haxaml_setup", "invalid_setup_args", str(exc))

    return _ok(
        "haxaml_setup",
        setup_data(plan, apply_result=apply_result),
        warnings=plan.warnings,
        detail=detail_mode,
    )


@mcp_app.tool()
def haxaml_reconcile(project_dir: str = ".", detail: str = DETAIL_SHORT) -> dict:
    """Return structured derivation-boundary conflict report."""
    detail_mode, detail_err = _normalize_detail("haxaml_reconcile", detail)
    if detail_err:
        return detail_err

    report = reconcile_derivation(project_dir)
    if report["severity_totals"]["blocking"] > 0:
        return _gate_error_with_retry_policy(
            "haxaml_reconcile",
            "derivation_conflicts",
            report["human_summary"],
            project_dir=project_dir,
            details=report,
        )
    _retry_guard_clear(project_dir, tool="haxaml_validate", error_code="derivation_conflicts")
    _retry_guard_clear(project_dir, tool="haxaml_session_record", error_code="derivation_conflicts")
    _retry_guard_clear(project_dir, tool="haxaml_reconcile", error_code="derivation_conflicts")
    return _ok(
        "haxaml_reconcile",
        {
            "message": report["human_summary"],
            **report,
        },
        detail=detail_mode,
    )


@mcp_app.tool()
def haxaml_needs(project_dir: str = ".", detail: str = DETAIL_SHORT) -> dict:
    """List what the user still needs to provide.

    Checks for blocking unresolved items in facts.yaml,
    blocking dependencies in acts.yaml, active run requirements
    in expect.yaml, and blocking open questions.
    """
    detail_mode, detail_err = _normalize_detail("haxaml_needs", detail)
    if detail_err:
        return detail_err

    message = render_needs(project_dir)
    if message.startswith("✗"):
        return _err("haxaml_needs", "missing_frame", message)
    return _ok("haxaml_needs", {"message": message}, detail=detail_mode)


@mcp_app.tool()
def haxaml_impact(module: str, project_dir: str = ".", detail: str = DETAIL_SHORT) -> dict:
    """Check what's affected by changing a module.

    Reads map.yaml to show module ownership, dependencies, and impact rules.
    This prevents the "fix kitchen, break bathroom" problem.
    """
    detail_mode, detail_err = _normalize_detail("haxaml_impact", detail)
    if detail_err:
        return detail_err

    message = render_impact(module, project_dir)
    if message.startswith("✗"):
        return _err("haxaml_impact", "impact_unavailable", message)
    return _ok("haxaml_impact", {"message": message, "module": module}, detail=detail_mode)


@mcp_app.tool()
def haxaml_state_show(project_dir: str = ".", detail: str = DETAIL_SHORT) -> dict:
    """Show current project diary (acts.yaml) summary."""
    detail_mode, detail_err = _normalize_detail("haxaml_state_show", detail)
    if detail_err:
        return detail_err

    p = Path(project_dir).resolve()
    acts_path = resolve_frame_file(p, "acts.yaml")
    if not acts_path:
        return _err("haxaml_state_show", "missing_acts", "acts.yaml not found")

    try:
        sm = StateManager(str(acts_path))
    except StateError as e:
        return _err("haxaml_state_show", "state_error", str(e))

    stats = sm.get_stats()
    message = (
        f"Phase:      {stats['current_phase']}\n"
        f"Active:     {stats['active_task']}\n"
        f"Completed:  {stats['completed_count']}\n"
        f"Blocked:    {stats['blocked_count']}\n"
        f"Decisions:  {stats['decision_count']}\n"
        f"Unresolved: {stats['unresolved_count']}\n"
        f"Runs:       {stats['run_count']} hot / {stats['archived_run_count']} archived\n"
        f"Sessions:   {stats['session_count']} hot / {stats['archived_session_count']} archived\n"
        f"Verify:     {stats['verification_count']} hot / {stats['archived_verification_count']} archived\n"
        f"Archive:    {stats['archive_mode']}\n"
        f"File size:  {stats['file_size_bytes']} bytes"
    )
    return _ok("haxaml_state_show", {"message": message, "stats": stats}, detail=detail_mode)


@mcp_app.tool()
def haxaml_state_compact(
    project_dir: str = ".",
    keep_recent: int = 5,
    dry_run: bool = False,
    detail: str = DETAIL_SHORT,
) -> dict:
    """Archive cold runs, sessions, and verifications out of hot acts state."""
    detail_mode, detail_err = _normalize_detail("haxaml_state_compact", detail)
    if detail_err:
        return detail_err

    p = Path(project_dir).resolve()
    acts_path = resolve_frame_file(p, "acts.yaml")
    if not acts_path:
        return _err("haxaml_state_compact", "missing_acts", "acts.yaml not found")

    try:
        sm = StateManager(str(acts_path))
        result = sm.compact(keep_recent=keep_recent, dry_run=dry_run)
    except StateError as e:
        return _err("haxaml_state_compact", "state_error", str(e))

    message = (
        f"Archive preview complete." if dry_run else "Archive complete."
    )
    message += (
        f" archived runs={result['archived']['runs']},"
        f" sessions={result['archived']['sessions']},"
        f" verifications={result['archived']['verifications']}."
    )
    return _ok("haxaml_state_compact", {"message": message, "result": result}, detail=detail_mode)
