"""MCP ops tools for Haxaml."""

from haxaml.mcp.base import *


@mcp_app.tool()
def haxaml_export(
    agent: str = "generic",
    project_dir: str = ".",
    target: Optional[str] = None,
    dry_run: bool = False,
    diff_preview: bool = False,
    override_native: bool = False,
    overwrite_existing: bool = False,
    detail: str = DETAIL_SHORT,
) -> dict:
    """Export FRAME to an agent-native markdown file.

    Default export writes HAXAML.md. Explicit agent exports can generate
    CLAUDE.md, haxaml-agents.md, .cursor/rules/haxaml.mdc, etc.
    Use agent='all' to export for all supported agents.

    Supported agents: claude, codex, cursor, windsurf, copilot, gemini, generic
    """
    detail_mode, detail_err = _normalize_detail("haxaml_export", detail)
    if detail_err:
        return detail_err

    target_path = (target or "").strip() or None

    if agent == "all":
        if target_path is not None:
            return _err(
                "haxaml_export",
                "invalid_target_with_all",
                "target cannot be used with agent='all'.",
            )
        if dry_run:
            return _err(
                "haxaml_export",
                "invalid_dry_run_with_all",
                "dry_run is only supported with a single agent.",
            )
        lines = []
        exported = []
        # Multi-agent export intentionally writes one canonical file per agent;
        # we do not try to merge them into a shared target path.
        for a in list_agents():
            path = export_to_file(
                project_dir,
                a["name"],
                override_native=override_native,
                overwrite_existing=overwrite_existing,
            )
            lines.append(f"✓ {a['name']:10s} → {path}")
            exported.append({"agent": a["name"], "path": path})
        return _ok(
            "haxaml_export",
            {"message": "\n".join(lines), "exports": exported},
            detail=detail_mode,
        )

    if agent not in AGENT_CONFIGS:
        available = ", ".join(a["name"] for a in list_agents())
        return _err(
            "haxaml_export",
            "unknown_agent",
            f"Unknown agent '{agent}'. Available: {available}",
        )

    resolved_target = _resolve_export_target(
        project_dir=project_dir,
        agent=agent,
        target=target_path,
        override_native=override_native,
    )
    content = export_frame_to_markdown(project_dir, agent)

    existing = ""
    exists = resolved_target.exists()
    if exists:
        existing = resolved_target.read_text(encoding="utf-8", errors="ignore")

    diff = ""
    summary = {"changed": not exists or existing != content, "added_lines": 0, "removed_lines": 0}
    if diff_preview:
        diff = _build_unified_diff(existing, content, resolved_target)
        summary = _diff_summary(diff)

    if dry_run:
        message = f"✓ Dry run complete for {resolved_target}"
        return _ok(
            "haxaml_export",
            {
                "message": message,
                "agent": agent,
                "would_write": True,
                "target_path": str(resolved_target),
                "exists": exists,
                "generated_marker_present": ("Generated by Haxaml from FRAME" in existing) if exists else False,
                "diff": diff,
                "summary": summary,
            },
            detail=detail_mode,
        )

    try:
        path = export_to_file(
            project_dir,
            agent,
            output_path=target_path,
            override_native=override_native,
            overwrite_existing=overwrite_existing,
        )
        message = f"✓ Exported to {path}"
        return _ok(
            "haxaml_export",
            {
                "message": message,
                "agent": agent,
                "target_path": path,
                "exists": exists,
                "generated_marker_present": ("Generated by Haxaml from FRAME" in existing) if exists else False,
                "diff": diff if diff_preview else "",
                "summary": summary if diff_preview else {"changed": True, "added_lines": 0, "removed_lines": 0},
            },
            detail=detail_mode,
        )
    except FileExistsError as e:
        return _err("haxaml_export", "protected_existing_file", str(e))


@mcp_app.tool()
def haxaml_upgrade(
    target_version: Optional[str] = None,
    include_mcp: bool = True,
    dry_run: bool = False,
    detail: str = DETAIL_SHORT,
) -> dict:
    """Upgrade haxaml (and optionally haxaml-mcp) using uv tool management."""
    detail_mode, detail_err = _normalize_detail("haxaml_upgrade", detail)
    if detail_err:
        return detail_err

    if not shutil.which("uv"):
        return _err(
            "haxaml_upgrade",
            "uv_not_found",
            "uv is required for upgrade. Install uv first: https://docs.astral.sh/uv/",
        )

    specs = [version_spec(PACKAGE_NAME, target_version)]
    if include_mcp:
        specs.append(version_spec(MCP_LAUNCHER_PACKAGE, target_version))

    upgrade_cmd = ["uv", "tool", "upgrade", *specs]
    if dry_run:
        return _ok(
            "haxaml_upgrade",
            {
                "message": "✓ Dry run upgrade plan prepared.",
                "command": upgrade_cmd,
                "target_version": target_version or "latest",
                "include_mcp": include_mcp,
            },
            detail=detail_mode,
        )

    primary = subprocess.run(upgrade_cmd, capture_output=True, text=True)
    if primary.returncode == 0:
        return _ok(
            "haxaml_upgrade",
            {
                "message": "✓ Upgrade complete via `uv tool upgrade`.",
                "command": upgrade_cmd,
                "stdout": (primary.stdout or "").strip(),
                "stderr": (primary.stderr or "").strip(),
                "include_mcp": include_mcp,
                "target_version": target_version or "latest",
            },
            detail=detail_mode,
        )

    # Older uv versions or partial tool installs can make the bulk upgrade fail
    # even though per-package upgrade/install still works, so we fall back to
    # one spec at a time before declaring the operation failed.
    failures = []
    executed = []
    for spec in specs:
        cmd = ["uv", "tool", "install", "--upgrade", spec]
        step = subprocess.run(cmd, capture_output=True, text=True)
        executed.append({"command": cmd, "returncode": step.returncode})
        if step.returncode != 0:
            failures.append(
                {
                    "spec": spec,
                    "stderr": (step.stderr or "").strip(),
                    "stdout": (step.stdout or "").strip(),
                }
            )

    if failures:
        return _err(
            "haxaml_upgrade",
            "upgrade_failed",
            "Upgrade failed for one or more packages.",
            {
                "command": upgrade_cmd,
                "primary_stderr": (primary.stderr or "").strip(),
                "primary_stdout": (primary.stdout or "").strip(),
                "failures": failures,
                "executed": executed,
            },
        )

    return _ok(
        "haxaml_upgrade",
        {
            "message": "✓ Upgrade complete via fallback install flow.",
            "command": upgrade_cmd,
            "include_mcp": include_mcp,
            "target_version": target_version or "latest",
            "executed": executed,
        },
        detail=detail_mode,
    )


@mcp_app.tool()
def haxaml_mcp_bootstrap(
    project_dir: str = ".",
    editors: Optional[list[str]] = None,
    mode: str = "both",
    uvx: bool = True,
    overwrite: bool = False,
    detail: str = DETAIL_SHORT,
) -> dict:
    """Generate and optionally write MCP config snippets for common editors."""
    detail_mode, detail_err = _normalize_detail("haxaml_mcp_bootstrap", detail)
    if detail_err:
        return detail_err

    valid_modes = {"snippets", "write", "both"}
    if mode not in valid_modes:
        return _err(
            "haxaml_mcp_bootstrap",
            "invalid_mode",
            f"mode must be one of: {', '.join(sorted(valid_modes))}",
        )

    requested = editors or ["claude_code", "cursor", "copilot", "generic"]
    supported = {"claude_code", "cursor", "copilot", "generic"}
    unknown = [e for e in requested if e not in supported]
    if unknown:
        return _err(
            "haxaml_mcp_bootstrap",
            "unknown_editor",
            "Unsupported editor requested.",
            {"unknown_editors": unknown, "supported_editors": sorted(supported)},
        )

    project = Path(project_dir).resolve()
    server_block = _mcp_server_config(str(project), uvx=uvx)
    snippet = {"mcpServers": {"haxaml": server_block}}
    snippets = {editor: snippet for editor in requested}
    writes = []

    if mode in {"write", "both"}:
        targets = _editor_targets(project)
        seen_paths = set()
        for editor in requested:
            target_path = targets.get(editor)
            if target_path is None:
                writes.append(
                    {
                        "editor": editor,
                        "path": None,
                        "status": "skipped_unknown_location",
                        "message": "No safe project-local target path is defined for this editor.",
                    }
                )
                continue
            # Some editor aliases intentionally share the same project-local
            # config file; only write it once per bootstrap run.
            if str(target_path) in seen_paths:
                writes.append(
                    {
                        "editor": editor,
                        "path": str(target_path),
                        "status": "skipped_duplicate_target",
                        "message": "Target already handled for another requested editor.",
                    }
                )
                continue
            seen_paths.add(str(target_path))
            status, message = _write_bootstrap_config(target_path, server_block, overwrite=overwrite)
            writes.append(
                {
                    "editor": editor,
                    "path": str(target_path),
                    "status": status,
                    "message": message,
                }
            )

    message = "✓ MCP bootstrap prepared."
    if mode in {"write", "both"}:
        written_count = sum(1 for item in writes if item["status"] == "written")
        message += f" Wrote {written_count} config file(s)."

    return _ok(
        "haxaml_mcp_bootstrap",
        {
            "message": message,
            "project_dir": str(project),
            "mode": mode,
            "snippets": snippets if mode in {"snippets", "both"} else {},
            "writes": writes,
            "next_steps": [
                "Use `/mcp show` (or equivalent) in your client to verify server visibility.",
                "For Copilot CLI global setup, see ~/.copilot/mcp-config.json docs path.",
            ],
        },
        detail=detail_mode,
    )


@mcp_app.tool()
def haxaml_adopt_plan(project_dir: str = ".", detail: str = DETAIL_SHORT) -> dict:
    """Inventory native instruction files and return non-destructive adoption plan."""
    detail_mode, detail_err = _normalize_detail("haxaml_adopt_plan", detail)
    if detail_err:
        return detail_err

    payload, warnings = _adoption_plan_payload(project_dir)
    return _ok(
        "haxaml_adopt_plan",
        {
            "message": payload["human_summary"],
            **payload,
        },
        warnings=warnings,
        detail=detail_mode,
    )


@mcp_app.tool()
def haxaml_reconcile(project_dir: str = ".", detail: str = DETAIL_SHORT) -> dict:
    """Return structured derivation-boundary conflict report."""
    detail_mode, detail_err = _normalize_detail("haxaml_reconcile", detail)
    if detail_err:
        return detail_err

    report = reconcile_derivation(project_dir)
    if report["severity_totals"]["blocking"] > 0:
        return _gate_error_with_retry_policy(
            "haxaml_reconcile",
            "derivation_conflicts",
            report["human_summary"],
            project_dir=project_dir,
            details=report,
        )
    _retry_guard_clear(project_dir, tool="haxaml_validate", error_code="derivation_conflicts")
    _retry_guard_clear(project_dir, tool="haxaml_session_record", error_code="derivation_conflicts")
    _retry_guard_clear(project_dir, tool="haxaml_reconcile", error_code="derivation_conflicts")
    return _ok(
        "haxaml_reconcile",
        {
            "message": report["human_summary"],
            **report,
        },
        detail=detail_mode,
    )


@mcp_app.tool()
def haxaml_adopt(
    project_dir: str = ".",
    write: bool = False,
    force: bool = False,
    detail: str = DETAIL_SHORT,
) -> dict:
    """Adopt an existing project into FRAME governance.

    Scans for native agent files (CLAUDE.md, AGENTS.md, .cursor/rules/, etc.)
    and repository context (README, package.json, etc.).

    With write=False (default): shows the adoption report (dry run).
    With write=True: creates .haxaml/ADOPTION.md and scaffold FRAME files.
    """
    detail_mode, detail_err = _normalize_detail("haxaml_adopt", detail)
    if detail_err:
        return detail_err

    plan = scan_native_sources(project_dir)
    plan_payload, plan_warnings = _adoption_plan_payload(project_dir, plan=plan)

    if not write:
        report = render_adoption_report(plan)
        return _ok(
            "haxaml_adopt",
            {
                "message": f"{report}\n---\nDry run. Call with write=True to create files.",
                "written": [],
                "dry_run": True,
                "adoption_plan": plan_payload,
            },
            warnings=[
                "Prefer haxaml_adopt_plan for non-destructive inventory and migration planning.",
                *plan_warnings,
            ],
            detail=detail_mode,
        )

    written = write_adoption_scaffold(plan, force=force)
    if written:
        lines = []
        for path in written:
            lines.append(f"✓ wrote {path.relative_to(plan.project_dir)}")
        if plan.existing_frame_files and not force:
            lines.append(f"Preserved existing: {', '.join(plan.existing_frame_files)}")
        lines.append(
            "Next: fill in scaffold unknowns with real project facts, "
            "then call haxaml_validate"
        )
        return _ok(
            "haxaml_adopt",
            {
                "message": "\n".join(lines),
                "written": [str(path.relative_to(plan.project_dir)) for path in written],
                "dry_run": False,
                "adoption_plan": plan_payload,
            },
            warnings=[
                "Use haxaml_reconcile after edits to detect map-canonical derivation conflicts.",
                *plan_warnings,
            ],
            detail=detail_mode,
        )

    return _ok(
        "haxaml_adopt",
        {
            "message": "No files written. Existing files preserved. Use force=True to overwrite.",
            "written": [],
            "dry_run": False,
            "adoption_plan": plan_payload,
        },
        warnings=[
            "Use haxaml_adopt_plan for non-destructive planning before forceful writes.",
            *plan_warnings,
        ],
        detail=detail_mode,
    )


@mcp_app.tool()
def haxaml_needs(project_dir: str = ".", detail: str = DETAIL_SHORT) -> dict:
    """List what the user still needs to provide.

    Checks for blocking unresolved items in facts.yaml,
    blocking dependencies in acts.yaml, active run requirements
    in expect.yaml, and blocking open questions.
    """
    detail_mode, detail_err = _normalize_detail("haxaml_needs", detail)
    if detail_err:
        return detail_err

    message = render_needs(project_dir)
    if message.startswith("✗"):
        return _err("haxaml_needs", "missing_frame", message)
    return _ok("haxaml_needs", {"message": message}, detail=detail_mode)


@mcp_app.tool()
def haxaml_impact(module: str, project_dir: str = ".", detail: str = DETAIL_SHORT) -> dict:
    """Check what's affected by changing a module.

    Reads map.yaml to show module ownership, dependencies, and impact rules.
    This prevents the "fix kitchen, break bathroom" problem.
    """
    detail_mode, detail_err = _normalize_detail("haxaml_impact", detail)
    if detail_err:
        return detail_err

    message = render_impact(module, project_dir)
    if message.startswith("✗"):
        return _err("haxaml_impact", "impact_unavailable", message)
    return _ok("haxaml_impact", {"message": message, "module": module}, detail=detail_mode)


@mcp_app.tool()
def haxaml_state_show(project_dir: str = ".", detail: str = DETAIL_SHORT) -> dict:
    """Show current project diary (acts.yaml) summary."""
    detail_mode, detail_err = _normalize_detail("haxaml_state_show", detail)
    if detail_err:
        return detail_err

    p = Path(project_dir).resolve()
    acts_path = resolve_frame_file(p, "acts.yaml")
    if not acts_path:
        return _err("haxaml_state_show", "missing_acts", "acts.yaml not found")

    try:
        sm = StateManager(str(acts_path))
    except StateError as e:
        return _err("haxaml_state_show", "state_error", str(e))

    stats = sm.get_stats()
    message = (
        f"Phase:      {stats['current_phase']}\n"
        f"Active:     {stats['active_task']}\n"
        f"Completed:  {stats['completed_count']}\n"
        f"Blocked:    {stats['blocked_count']}\n"
        f"Decisions:  {stats['decision_count']}\n"
        f"Unresolved: {stats['unresolved_count']}\n"
        f"Runs:       {stats['run_count']} (+ {stats['total_runs_compacted']} compacted)\n"
        f"File size:  {stats['file_size_bytes']} bytes"
    )
    return _ok("haxaml_state_show", {"message": message, "stats": stats}, detail=detail_mode)


@mcp_app.tool()
def haxaml_state_compact(
    project_dir: str = ".",
    keep_recent: int = 5,
    detail: str = DETAIL_SHORT,
) -> dict:
    """Compact old runs in acts.yaml to save context tokens.

    Summarizes old runs and keeps only the most recent ones.
    """
    detail_mode, detail_err = _normalize_detail("haxaml_state_compact", detail)
    if detail_err:
        return detail_err

    p = Path(project_dir).resolve()
    acts_path = resolve_frame_file(p, "acts.yaml")
    if not acts_path:
        return _err("haxaml_state_compact", "missing_acts", "acts.yaml not found")

    try:
        sm = StateManager(str(acts_path))
        result = sm.compact(keep_recent=keep_recent)
    except StateError as e:
        return _err("haxaml_state_compact", "state_error", str(e))

    message = f"✓ Compacted {result['compacted']} runs, kept {result['kept']}"
    return _ok("haxaml_state_compact", {"message": message, "result": result}, detail=detail_mode)
