"""Tests for MCP ops tools."""

from unittest.mock import patch

import yaml

from haxaml.mcp_server import (
    haxaml_adopt,
    haxaml_adopt_plan,
    haxaml_export,
    haxaml_impact,
    haxaml_mcp_bootstrap,
    haxaml_needs,
    haxaml_reconcile,
    haxaml_state_compact,
    haxaml_state_show,
    haxaml_upgrade,
)

from .helpers import msg as _msg


RECONCILE_REQUIRED_GUIDANCE_FIELDS = {
    "fix_confidence",
    "safe_to_auto_apply",
    "related_files",
    "why_it_matters",
    "suggested_next_tool",
}


class TestExport:
    def test_export_generic(self, governed_project):
        result = haxaml_export("generic", str(governed_project))
        assert result["ok"] is True
        assert "Exported to" in _msg(result)
        assert (governed_project / "HAXAML.md").exists()

    def test_export_claude(self, governed_project):
        result = haxaml_export("claude", str(governed_project))
        assert result["ok"] is True
        assert "Exported to" in _msg(result)
        assert (governed_project / "CLAUDE.md").exists()

    def test_export_all(self, governed_project):
        result = haxaml_export("all", str(governed_project))
        text = _msg(result)
        assert result["ok"] is True
        assert "claude" in text
        assert "codex" in text
        assert "cursor" in text

    def test_export_invalid_agent(self, governed_project):
        result = haxaml_export("nonexistent", str(governed_project))
        assert result["ok"] is False

    def test_export_codex_defaults_to_haxaml_agents(self, governed_project):
        result = haxaml_export("codex", str(governed_project))
        assert result["ok"] is True
        assert "Exported to" in _msg(result)
        assert (governed_project / "haxaml-agents.md").exists()

    def test_export_codex_override_native_replaces_agents_md(self, governed_project):
        native = governed_project / "AGENTS.md"
        native.write_text("human-written file\n", encoding="utf-8")

        result = haxaml_export(
            "codex",
            str(governed_project),
            override_native=True,
        )
        assert result["ok"] is True
        assert "Exported to" in _msg(result)
        assert "Generated by Haxaml from FRAME" in native.read_text(encoding="utf-8")

    def test_export_target_writes_custom_path(self, governed_project):
        custom = governed_project / "TEAM_GUIDE.md"
        result = haxaml_export(
            "generic",
            str(governed_project),
            target=str(custom),
        )
        assert result["ok"] is True
        assert "Exported to" in _msg(result)
        assert custom.exists()
        assert "Generated by Haxaml from FRAME" in custom.read_text(encoding="utf-8")

    def test_export_all_rejects_target(self, governed_project):
        result = haxaml_export(
            "all",
            str(governed_project),
            target="TEAM_GUIDE.md",
        )
        assert result["ok"] is False
        assert "target cannot be used with agent='all'" in result["error"]["message"]

    def test_export_dry_run_does_not_write(self, governed_project):
        target = governed_project / "PREVIEW.md"
        result = haxaml_export(
            "generic",
            str(governed_project),
            target=str(target),
            dry_run=True,
            diff_preview=True,
        )
        assert result["ok"] is True
        assert target.exists() is False
        assert result["data"]["would_write"] is True
        assert isinstance(result["data"]["diff"], str)


class TestBootstrap:
    def test_bootstrap_snippets_only(self, governed_project):
        result = haxaml_mcp_bootstrap(str(governed_project), mode="snippets")
        assert result["ok"] is True
        assert "snippets" in result["data"]
        assert result["data"]["writes"] == []

    def test_bootstrap_write_mode(self, governed_project):
        result = haxaml_mcp_bootstrap(
            str(governed_project),
            editors=["generic"],
            mode="write",
        )
        assert result["ok"] is True
        statuses = [w["status"] for w in result["data"]["writes"]]
        assert "written" in statuses or "skipped_exists" in statuses
        assert (governed_project / ".mcp.json").exists()


class TestUpgrade:
    def test_upgrade_dry_run(self):
        result = haxaml_upgrade(target_version="9.9.9", dry_run=True)
        assert result["ok"] is True
        assert result["data"]["command"][:3] == ["uv", "tool", "upgrade"]
        assert "haxaml==9.9.9" in result["data"]["command"]

    @patch("haxaml.mcp_server.shutil.which", return_value=None)
    def test_upgrade_requires_uv(self, _which):
        result = haxaml_upgrade()
        assert result["ok"] is False
        assert result["error"]["code"] == "uv_not_found"


class TestAdopt:
    def test_dry_run(self, tmp_path):
        (tmp_path / "CLAUDE.md").write_text("# Rules\nUse pytest.\n")
        (tmp_path / "README.md").write_text("# Project\n")
        result = haxaml_adopt(str(tmp_path), write=False)
        text = _msg(result)
        assert result["ok"] is True
        assert "Dry run" in text
        assert "CLAUDE.md" in text

    def test_write(self, tmp_path):
        (tmp_path / "CLAUDE.md").write_text("# Rules\nUse pytest.\n")
        result = haxaml_adopt(str(tmp_path), write=True)
        assert result["ok"] is True
        assert "wrote" in _msg(result)
        assert (tmp_path / ".haxaml" / "ADOPTION.md").exists()


class TestAdoptPlan:
    def test_returns_non_destructive_inventory(self, tmp_path):
        (tmp_path / "CLAUDE.md").write_text("# Rules\nUse tests.\n")
        (tmp_path / "README.md").write_text("# Project\n")
        result = haxaml_adopt_plan(str(tmp_path))
        assert result["ok"] is True
        data = result["data"]
        assert data["non_destructive"] is True
        assert data["counts"]["native_files"] >= 1
        assert "instruction_analysis" in data
        assert data["instruction_analysis"]["counts"]["sources_scanned"] >= 1
        assert "human_summary" in data
        assert (tmp_path / ".haxaml").exists() is False

    def test_reports_conflicts_and_duplicates_with_warnings(self, tmp_path):
        (tmp_path / "CLAUDE.md").write_text(
            "# Claude Rules\n- Always run tests before commit.\n",
            encoding="utf-8",
        )
        (tmp_path / "AGENTS.md").write_text(
            "# Codex Rules\n- Do not run tests before commit.\n",
            encoding="utf-8",
        )
        (tmp_path / "README.md").write_text(
            "# Project\n\n## Agent Instructions\n- Always run tests before commit.\n",
            encoding="utf-8",
        )

        result = haxaml_adopt_plan(str(tmp_path))
        assert result["ok"] is True
        assert result["warnings"]

        data = result["data"]
        analysis = data["instruction_analysis"]
        assert analysis["counts"]["conflicts"] >= 1
        assert analysis["counts"]["duplicates"] >= 1
        assert analysis["precedence_decision_required"] is True
        assert analysis["counts"]["readme_sections_scanned"] >= 1
        assert analysis["precedence_candidates"]

        first_conflict = analysis["conflicts"][0]
        assert first_conflict["severity"] == "warning"
        assert first_conflict["category"] in ("precedence_conflict", "cross_source_rule_conflict")
        assert first_conflict["requires_user_choice"] is True
        assert first_conflict["recommended_next_action"] == "decide_authoritative_source_then_update_frame"
        assert all("snippet" not in src["scope"].lower() for src in first_conflict["sources"])

        first_duplicate = analysis["duplicates"][0]
        assert first_duplicate["sources"]
        assert all("snippet" not in src["scope"].lower() for src in first_duplicate["sources"])

    def test_detects_cursor_rules_directory_files(self, tmp_path):
        rules_dir = tmp_path / ".cursor" / "rules"
        rules_dir.mkdir(parents=True)
        (rules_dir / "policy.txt").write_text("- Always document changes.\n", encoding="utf-8")

        result = haxaml_adopt_plan(str(tmp_path))
        assert result["ok"] is True
        paths = [item["path"] for item in result["data"]["native_files"]]
        assert ".cursor/rules/policy.txt" in paths


class TestReconcile:
    def test_optional_map_deferred_when_absent(self, governed_project):
        result = haxaml_reconcile(str(governed_project), detail="full")
        assert result["ok"] is True
        assert result["data"]["deferred_map_canonical_checks"] is True
        assert result["data"]["conflict_counts"]["blocking"] == 0

    def test_done_phase_with_active_run_is_advisory_only(self, governed_project):
        expect_path = governed_project / ".haxaml" / "expect.yaml"
        expect = yaml.safe_load(expect_path.read_text())
        expect["phases"][0]["status"] = "done"
        expect_path.write_text(yaml.dump(expect, default_flow_style=False, sort_keys=False))

        result = haxaml_reconcile(str(governed_project), detail="full")
        assert result["ok"] is True
        assert result["data"]["warning_counts"]["total"] >= 1
        assert any(
            conflict["category"] == "phase_run_sync"
            for conflict in result["data"]["conflicts"]
        )

    def test_returns_blocking_conflicts_when_map_present_and_misaligned(self, governed_project):
        map_data = {
            "modules": [
                {"name": "auth", "purpose": "Auth", "files": ["src/auth/"]},
                {"name": "api", "purpose": "API", "files": ["src/api/"]},
            ],
            "dependencies": [{"from": "api", "to": "auth", "reason": "auth middleware"}],
            "impact": [{"when": "auth", "check": ["api tests"]}],
        }
        (governed_project / ".haxaml" / "map.yaml").write_text(
            yaml.dump(map_data, default_flow_style=False, sort_keys=False)
        )

        result = haxaml_reconcile(str(governed_project))
        assert result["ok"] is False
        assert result["error"]["code"] == "derivation_conflicts"
        assert result["error"]["details"]["severity_totals"]["blocking"] > 0

        conflicts = result["error"]["details"]["conflicts"]
        assert conflicts
        allowed_confidence = {"low", "medium", "high"}
        allowed_next_tool = {
            "haxaml_validate",
            "haxaml_doctor",
            "haxaml_impact",
            "haxaml_session_verify",
            "haxaml_context_pack",
            "manual_edit",
        }
        for conflict in conflicts:
            assert RECONCILE_REQUIRED_GUIDANCE_FIELDS.issubset(conflict.keys())
            assert conflict["fix_confidence"] in allowed_confidence
            assert conflict["safe_to_auto_apply"] is False
            assert conflict["suggested_next_tool"] in allowed_next_tool
            assert isinstance(conflict["related_files"], list)
            assert len(conflict["related_files"]) > 0
            assert conflict["related_files"] == sorted(conflict["related_files"])
            assert all(isinstance(item, str) and item for item in conflict["related_files"])
            assert isinstance(conflict["why_it_matters"], str)
            assert conflict["why_it_matters"].strip()

    def test_deterministic_summary_for_equivalent_state(self, governed_project):
        map_data = {
            "modules": [
                {"name": "auth", "purpose": "Auth", "files": ["src/auth/"]},
                {"name": "api", "purpose": "API", "files": ["src/api/"]},
            ],
            "dependencies": [{"from": "api", "to": "auth", "reason": "auth middleware"}],
            "impact": [{"when": "auth", "check": ["api tests"]}],
        }
        (governed_project / ".haxaml" / "map.yaml").write_text(
            yaml.dump(map_data, default_flow_style=False, sort_keys=False)
        )

        first = haxaml_reconcile(str(governed_project))
        second = haxaml_reconcile(str(governed_project))
        first_details = first["error"]["details"]
        second_details = second["error"]["details"]
        assert second["error"]["code"] in ("derivation_conflicts", "retry_policy_blocked")
        assert first_details["human_summary"] == second_details["human_summary"]
        assert first_details["conflicts"] == second_details["conflicts"]


class TestNeeds:
    def test_no_blocking_needs(self, governed_project):
        result = haxaml_needs(str(governed_project))
        text = _msg(result)
        assert result["ok"] is True
        assert "ready to build" in text or "Non-blocking" in text or "Active run" in text

    def test_blocking_unresolved(self, governed_project):
        facts_path = governed_project / ".haxaml" / "facts.yaml"
        facts = yaml.safe_load(facts_path.read_text())
        facts["unresolved"] = [{"item": "DB URI", "reason": "Need production URI", "blocking": True}]
        facts_path.write_text(yaml.dump(facts, default_flow_style=False, sort_keys=False))

        result = haxaml_needs(str(governed_project))
        assert result["ok"] is True
        assert "Blocking" in _msg(result)
        assert "DB URI" in _msg(result)

    def test_missing_project(self, tmp_path):
        result = haxaml_needs(str(tmp_path))
        assert "facts.yaml not found" in _msg(result)


class TestImpact:
    def test_no_map(self, governed_project):
        result = haxaml_impact("auth", str(governed_project))
        assert result["ok"] is True
        assert "map.yaml not found" in _msg(result)

    def test_module_found(self, governed_project):
        map_data = {
            "modules": [
                {"name": "auth", "purpose": "Authentication", "files": ["src/auth/"]},
                {"name": "api", "purpose": "API routes", "files": ["src/api/"]},
            ],
            "dependencies": [
                {"from": "api", "to": "auth", "reason": "API needs auth middleware"},
            ],
            "impact": [
                {"when": "auth", "check": ["api tests", "middleware tests"]},
            ],
        }
        (governed_project / ".haxaml" / "map.yaml").write_text(
            yaml.dump(map_data, default_flow_style=False, sort_keys=False)
        )

        result = haxaml_impact("auth", str(governed_project))
        text = _msg(result)
        assert result["ok"] is True
        assert "Module: auth" in text
        assert "Authentication" in text
        assert "src/auth/" in text
        assert "api" in text
        assert "api tests" in text

    def test_module_not_found(self, governed_project):
        map_data = {
            "modules": [{"name": "auth", "purpose": "Auth", "files": []}],
            "dependencies": [],
            "impact": [],
        }
        (governed_project / ".haxaml" / "map.yaml").write_text(
            yaml.dump(map_data, default_flow_style=False, sort_keys=False)
        )

        result = haxaml_impact("nonexistent", str(governed_project))
        assert result["ok"] is False
        assert "not found" in result["error"]["message"]
        assert "auth" in result["error"]["message"]


class TestState:
    def test_show(self, governed_project):
        result = haxaml_state_show(str(governed_project))
        text = _msg(result)
        assert result["ok"] is True
        assert "Phase:" in text
        assert "Active:" in text
        assert "Completed:" in text

    def test_compact_no_runs(self, governed_project):
        result = haxaml_state_compact(str(governed_project))
        assert result["ok"] is True
        assert "archived runs=0" in _msg(result)

    def test_show_missing(self, tmp_path):
        result = haxaml_state_show(str(tmp_path))
        assert result["ok"] is False
        assert "not found" in result["error"]["message"]
