"""Tests for MCP ops tools."""

from unittest.mock import patch

import yaml

from haxaml.mcp_server import (
    haxaml_export,
    haxaml_impact,
    haxaml_needs,
    haxaml_reconcile,
    haxaml_setup,
    haxaml_state_compact,
    haxaml_state_show,
    haxaml_upgrade,
)

from .helpers import msg as _msg


RECONCILE_REQUIRED_GUIDANCE_FIELDS = {
    "fix_confidence",
    "safe_to_auto_apply",
    "related_files",
    "why_it_matters",
    "suggested_next_tool",
}


class TestExport:
    def test_export_generic(self, governed_project):
        result = haxaml_export("generic", str(governed_project))
        assert result["ok"] is True
        assert "Exported to" in _msg(result)
        assert (governed_project / "HAXAML.md").exists()

    def test_export_claude(self, governed_project):
        result = haxaml_export("claude", str(governed_project))
        assert result["ok"] is True
        assert "Exported to" in _msg(result)
        assert (governed_project / "CLAUDE.md").exists()

    def test_export_all(self, governed_project):
        result = haxaml_export("all", str(governed_project))
        text = _msg(result)
        assert result["ok"] is True
        assert "claude" in text
        assert "codex" in text
        assert "cursor" in text

    def test_export_invalid_agent(self, governed_project):
        result = haxaml_export("nonexistent", str(governed_project))
        assert result["ok"] is False

    def test_export_codex_defaults_to_haxaml_agents(self, governed_project):
        result = haxaml_export("codex", str(governed_project))
        assert result["ok"] is True
        assert "Exported to" in _msg(result)
        assert (governed_project / "haxaml-agents.md").exists()

    def test_export_codex_override_native_replaces_agents_md(self, governed_project):
        native = governed_project / "AGENTS.md"
        native.write_text("human-written file\n", encoding="utf-8")

        result = haxaml_export(
            "codex",
            str(governed_project),
            override_native=True,
        )
        assert result["ok"] is True
        assert "Exported to" in _msg(result)
        assert "Generated by Haxaml from FRAME" in native.read_text(encoding="utf-8")

    def test_export_target_writes_custom_path(self, governed_project):
        custom = governed_project / "TEAM_GUIDE.md"
        result = haxaml_export(
            "generic",
            str(governed_project),
            target=str(custom),
        )
        assert result["ok"] is True
        assert "Exported to" in _msg(result)
        assert custom.exists()
        assert "Generated by Haxaml from FRAME" in custom.read_text(encoding="utf-8")

    def test_export_all_rejects_target(self, governed_project):
        result = haxaml_export(
            "all",
            str(governed_project),
            target="TEAM_GUIDE.md",
        )
        assert result["ok"] is False
        assert "target cannot be used with agent='all'" in result["error"]["message"]

    def test_export_dry_run_does_not_write(self, governed_project):
        target = governed_project / "PREVIEW.md"
        result = haxaml_export(
            "generic",
            str(governed_project),
            target=str(target),
            dry_run=True,
            diff_preview=True,
        )
        assert result["ok"] is True
        assert target.exists() is False
        assert result["data"]["would_write"] is True
        assert isinstance(result["data"]["diff"], str)


class TestSetup:
    def test_auto_fresh_setup_writes_managed_files(self, tmp_path):
        result = haxaml_setup(project_dir=str(tmp_path))
        assert result["ok"] is True
        assert (tmp_path / ".haxaml" / "facts.yaml").exists()
        assert (tmp_path / "AGENTS.md").exists()
        assert (tmp_path / ".agents" / "skills" / "haxaml" / "SKILL.md").exists()
        assert result["data"]["apply_result"]["created"]

    def test_auto_mode_adopts_existing_native_files(self, tmp_path):
        (tmp_path / "CLAUDE.md").write_text("Existing Claude instructions.\n", encoding="utf-8")
        result = haxaml_setup(project_dir=str(tmp_path))
        assert result["ok"] is True
        assert (tmp_path / ".haxaml" / "adoption" / "adoption.yaml").exists()
        assert (tmp_path / ".haxaml" / "setup" / "targets" / "claude.md").exists()
        assert "HAXAML:MANAGED START" in (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")

    def test_auto_mode_with_weak_shared_signal_stays_fresh(self, tmp_path):
        (tmp_path / "AGENTS.md").write_text("Existing shared instructions.\n", encoding="utf-8")
        result = haxaml_setup(project_dir=str(tmp_path))
        assert result["ok"] is True
        assert (tmp_path / ".haxaml" / "adoption" / "adoption.yaml").exists() is False
        assert result["data"]["mode"] == "fresh"
        assert any("weak shared signals" in warning for warning in result["warnings"])

    def test_fresh_mode_preserves_existing_native_files(self, tmp_path):
        native = tmp_path / "CLAUDE.md"
        native.write_text("Existing Claude instructions.\n", encoding="utf-8")
        result = haxaml_setup(project_dir=str(tmp_path), mode="fresh")
        assert result["ok"] is True
        assert (tmp_path / ".haxaml" / "adoption" / "adoption.yaml").exists() is False
        assert "HAXAML:MANAGED START" not in native.read_text(encoding="utf-8")

    def test_user_scope_writes_only_home_surfaces(self, tmp_path, monkeypatch):
        home = tmp_path / "home"
        home.mkdir()
        monkeypatch.setenv("HOME", str(home))

        result = haxaml_setup(project_dir=str(tmp_path), scope="user", target="codex")
        assert result["ok"] is True
        assert (tmp_path / ".haxaml").exists() is False
        assert (home / ".codex" / "AGENTS.md").exists()
        assert (home / ".codex" / "config.toml").exists()

    def test_setup_tool_supports_workflow_assets(self, tmp_path):
        result = haxaml_setup(project_dir=str(tmp_path), target="claude", with_workflow=True)
        assert result["ok"] is True
        assert (tmp_path / ".haxaml" / "setup" / "workflows" / "claude" / "README.md").exists()
        assert (tmp_path / ".claude" / "settings.json").exists()


class TestUpgrade:
    def test_upgrade_dry_run(self):
        result = haxaml_upgrade(target_version="9.9.9", dry_run=True)
        assert result["ok"] is True
        assert result["data"]["command"][:3] == ["uv", "tool", "upgrade"]
        assert "haxaml==9.9.9" in result["data"]["command"]
        assert result["data"]["include_ui"] is False

    def test_upgrade_dry_run_can_include_ui(self):
        result = haxaml_upgrade(target_version="9.9.9", dry_run=True, include_ui=True)
        assert result["ok"] is True
        assert "haxaml-ui==9.9.9" in result["data"]["command"]
        assert result["data"]["include_ui"] is True

    @patch("haxaml.mcp_server.shutil.which", return_value=None)
    def test_upgrade_requires_uv(self, _which):
        result = haxaml_upgrade()
        assert result["ok"] is False
        assert result["error"]["code"] == "uv_not_found"


class TestReconcile:
    def test_optional_map_deferred_when_absent(self, governed_project):
        result = haxaml_reconcile(str(governed_project), detail="full")
        assert result["ok"] is True
        assert result["data"]["deferred_map_canonical_checks"] is True
        assert result["data"]["conflict_counts"]["blocking"] == 0

    def test_done_phase_with_active_run_is_advisory_only(self, governed_project):
        expect_path = governed_project / ".haxaml" / "expect.yaml"
        expect = yaml.safe_load(expect_path.read_text())
        expect["phases"][0]["status"] = "done"
        expect_path.write_text(yaml.dump(expect, default_flow_style=False, sort_keys=False))

        result = haxaml_reconcile(str(governed_project), detail="full")
        assert result["ok"] is True
        assert result["data"]["warning_counts"]["total"] >= 1
        assert any(
            conflict["category"] == "phase_run_sync"
            for conflict in result["data"]["conflicts"]
        )

    def test_returns_blocking_conflicts_when_map_present_and_misaligned(self, governed_project):
        map_data = {
            "modules": [
                {"name": "auth", "purpose": "Auth", "files": ["src/auth/"]},
                {"name": "api", "purpose": "API", "files": ["src/api/"]},
            ],
            "dependencies": [{"from": "api", "to": "auth", "reason": "auth middleware"}],
            "impact": [{"when": "auth", "check": ["api tests"]}],
        }
        (governed_project / ".haxaml" / "map.yaml").write_text(
            yaml.dump(map_data, default_flow_style=False, sort_keys=False)
        )

        result = haxaml_reconcile(str(governed_project))
        assert result["ok"] is False
        assert result["error"]["code"] == "derivation_conflicts"
        assert result["error"]["details"]["severity_totals"]["blocking"] > 0

        conflicts = result["error"]["details"]["conflicts"]
        assert conflicts
        allowed_confidence = {"low", "medium", "high"}
        allowed_next_tool = {
            "haxaml_validate",
            "haxaml_doctor",
            "haxaml_impact",
            "haxaml_session_verify",
            "haxaml_context_pack",
            "manual_edit",
        }
        for conflict in conflicts:
            assert RECONCILE_REQUIRED_GUIDANCE_FIELDS.issubset(conflict.keys())
            assert conflict["fix_confidence"] in allowed_confidence
            assert conflict["safe_to_auto_apply"] is False
            assert conflict["suggested_next_tool"] in allowed_next_tool
            assert isinstance(conflict["related_files"], list)
            assert len(conflict["related_files"]) > 0
            assert conflict["related_files"] == sorted(conflict["related_files"])
            assert all(isinstance(item, str) and item for item in conflict["related_files"])
            assert isinstance(conflict["why_it_matters"], str)
            assert conflict["why_it_matters"].strip()

    def test_deterministic_summary_for_equivalent_state(self, governed_project):
        map_data = {
            "modules": [
                {"name": "auth", "purpose": "Auth", "files": ["src/auth/"]},
                {"name": "api", "purpose": "API", "files": ["src/api/"]},
            ],
            "dependencies": [{"from": "api", "to": "auth", "reason": "auth middleware"}],
            "impact": [{"when": "auth", "check": ["api tests"]}],
        }
        (governed_project / ".haxaml" / "map.yaml").write_text(
            yaml.dump(map_data, default_flow_style=False, sort_keys=False)
        )

        first = haxaml_reconcile(str(governed_project))
        second = haxaml_reconcile(str(governed_project))
        first_details = first["error"]["details"]
        second_details = second["error"]["details"]
        assert second["error"]["code"] in ("derivation_conflicts", "retry_policy_blocked")
        assert first_details["human_summary"] == second_details["human_summary"]
        assert first_details["conflicts"] == second_details["conflicts"]


class TestNeeds:
    def test_no_blocking_needs(self, governed_project):
        result = haxaml_needs(str(governed_project))
        text = _msg(result)
        assert result["ok"] is True
        assert "ready to build" in text or "Non-blocking" in text or "Active run" in text

    def test_blocking_unresolved(self, governed_project):
        facts_path = governed_project / ".haxaml" / "facts.yaml"
        facts = yaml.safe_load(facts_path.read_text())
        facts["unresolved"] = [{"item": "DB URI", "reason": "Need production URI", "blocking": True}]
        facts_path.write_text(yaml.dump(facts, default_flow_style=False, sort_keys=False))

        result = haxaml_needs(str(governed_project))
        assert result["ok"] is True
        assert "Blocking" in _msg(result)
        assert "DB URI" in _msg(result)

    def test_missing_project(self, tmp_path):
        result = haxaml_needs(str(tmp_path))
        assert "facts.yaml not found" in _msg(result)


class TestImpact:
    def test_no_map(self, governed_project):
        result = haxaml_impact("auth", str(governed_project))
        assert result["ok"] is True
        assert "map.yaml not found" in _msg(result)

    def test_module_found(self, governed_project):
        map_data = {
            "modules": [
                {"name": "auth", "purpose": "Authentication", "files": ["src/auth/"]},
                {"name": "api", "purpose": "API routes", "files": ["src/api/"]},
            ],
            "dependencies": [
                {"from": "api", "to": "auth", "reason": "API needs auth middleware"},
            ],
            "impact": [
                {"when": "auth", "check": ["api tests", "middleware tests"]},
            ],
        }
        (governed_project / ".haxaml" / "map.yaml").write_text(
            yaml.dump(map_data, default_flow_style=False, sort_keys=False)
        )

        result = haxaml_impact("auth", str(governed_project))
        text = _msg(result)
        assert result["ok"] is True
        assert "Module: auth" in text
        assert "Authentication" in text
        assert "src/auth/" in text
        assert "api" in text
        assert "api tests" in text

    def test_module_not_found(self, governed_project):
        map_data = {
            "modules": [{"name": "auth", "purpose": "Auth", "files": []}],
            "dependencies": [],
            "impact": [],
        }
        (governed_project / ".haxaml" / "map.yaml").write_text(
            yaml.dump(map_data, default_flow_style=False, sort_keys=False)
        )

        result = haxaml_impact("nonexistent", str(governed_project))
        assert result["ok"] is False
        assert "not found" in result["error"]["message"]
        assert "auth" in result["error"]["message"]


class TestState:
    def test_show(self, governed_project):
        result = haxaml_state_show(str(governed_project))
        text = _msg(result)
        assert result["ok"] is True
        assert "Phase:" in text
        assert "Active:" in text
        assert "Completed:" in text

    def test_compact_no_runs(self, governed_project):
        result = haxaml_state_compact(str(governed_project))
        assert result["ok"] is True
        assert "archived runs=0" in _msg(result)

    def test_show_missing(self, tmp_path):
        result = haxaml_state_show(str(tmp_path))
        assert result["ok"] is False
        assert "not found" in result["error"]["message"]
