"""Canonical FRAME scaffold templates owned by setup."""

from __future__ import annotations

from pathlib import Path

from haxaml.paths import frame_path


FACTS_TEMPLATE = """\
# Project Facts (FRAME: F) — Generated by Haxaml
# 0.8.0 accepts only FRAME frontmatter. No body fields are valid in this slice.

frame:
  file: facts
  schema_version: 0.8.0
  role: stable_project_truth
  status: draft
  last_reviewed: null
  updated_by: null
  update_reason: null
"""

RULES_TEMPLATE = """\
# Project Rules (FRAME: R) — Generated by Haxaml
# 0.8.0 accepts only FRAME frontmatter. No body fields are valid in this slice.

frame:
  file: rules
  schema_version: 0.8.0
  role: project_constraints
  status: draft
  last_reviewed: null
  updated_by: null
  update_reason: null
"""

ACTS_TEMPLATE = """\
# Project Acts (FRAME: A) — Generated by Haxaml
# 0.8.0 accepts only FRAME frontmatter. Haxaml runtime state is stored outside this FRAME document.

frame:
  file: acts
  schema_version: 0.8.0
  role: checked_activity_record
  status: draft
  last_reviewed: null
  updated_by: null
  update_reason: null
"""

EXPECT_TEMPLATE = """\
# Project Expect (FRAME: E) — Generated by Haxaml
# 0.8.0 accepts only FRAME frontmatter. No body fields are valid in this slice.

frame:
  file: expect
  schema_version: 0.8.0
  role: planned_direction
  status: draft
  last_reviewed: null
  updated_by: null
  update_reason: null
"""


def render_frame_templates() -> dict[str, str]:
    """Return the canonical FRAME scaffold text."""
    return {
        "facts.yaml": FACTS_TEMPLATE,
        "rules.yaml": RULES_TEMPLATE,
        "acts.yaml": ACTS_TEMPLATE,
        "expect.yaml": EXPECT_TEMPLATE,
    }


def write_missing_frame_files(project_dir: Path) -> list[Path]:
    """Write missing FRAME scaffold files and return the created paths."""
    created: list[Path] = []
    for filename, content in render_frame_templates().items():
        path = frame_path(project_dir, filename)
        if path.exists():
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        created.append(path)
    return created
