"""Canonical FRAME scaffold templates owned by setup."""

from __future__ import annotations

from pathlib import Path

from haxaml.paths import frame_path
from haxaml.versioning import get_version


FACTS_TEMPLATE = """\
# Project Facts (FRAME: F) — Generated by Haxaml
# Fill in ALL required fields before running `haxaml validate`.

identity:
  name: ""
  version: ""
  description: ""

goal:
  purpose: ""
  scope: ""
  out_of_scope: []

stack:
  language: ""
  backend: ""
  frontend: ""
  runtime: ""
  package_manager: ""

architecture:
  pattern: ""
  reasoning: ""
  boundaries: []

database:
  type: ""
  connection: ""
  migrations: ""

tools:
  testing: ""
  mcp: []
  ci: ""
  other: []

services: []

constraints:
  - "Keep implementation changes scoped to the active task."

success_criteria:
  - "Task outcome is verified and recorded before claiming completion."

roles: []
features: []
unresolved: []
"""

RULES_TEMPLATE = """\
# Project Rules (FRAME: R) — Generated by Haxaml

governance:
  system: haxaml
  version: "__HAXAML_VERSION__"

before_task:
  read_first:
    - .haxaml/facts.yaml
    - .haxaml/rules.yaml
    - .haxaml/acts.yaml
  then_read:
    - .haxaml/expect.yaml
  check:
    - "Confirm the task matches project facts and current state."
    - "Read only source files relevant to the task."

boundaries:
  modules: {}
  rules:
    - "Edit only files relevant to the active task scope."

while_coding:
  constraints:
    - "Keep changes minimal and reversible where possible."
  discipline:
    - "Use short, accurate commit messages in plain language."
    - "Do not use commit prefixes like fix:, feat:, refactor:, chore:, or docs:."
    - "Run tests or validation for touched behavior."

after_task:
  report:
    - "Summarize what changed, why, and known risks."
  update:
    - ".haxaml/acts.yaml"
  verify:
    - "Run relevant tests or validation checks."

forbidden:
  - "Do not claim success without verification evidence."

escalation:
  act_independently:
    - "Small scoped implementation and test fixes."
  ask_first:
    - "Architecture changes, destructive data operations, or production-risk actions."

lifecycle:
  onboarding_full_reads: 5
  enforce_verify_before_record: true
  enforce_governed_evidence_on_validate: true
  phases:
    - prebuild
    - start
    - plan
    - context
    - act
    - verify
    - record
    - export

context_policy:
  default_pack: balanced
  max_items_per_section: 5
  max_chars_per_item: 240

memory_policy:
  archive_mode: manual
  max_hot_runs: 5
  max_hot_sessions: 5
  max_hot_verifications: 5
  max_acts_bytes: 16000
  keep_decisions_hot: true

clarification_policy:
  mode: risk_gated_soft_block
  min_task_chars: 16
  high_risk_keywords:
    - migrate
    - delete
    - auth
    - security
    - payment

verification_policy:
  require_checks:
    - understood_task
    - inspected_context
    - changed_right_files
    - risky_or_unrelated_touch
    - followed_rules
    - updated_journal
    - unresolved_logged
    - explained_changes
  allow_pass_with_risks: true

guidance_policy:
  task_type_hints: {}
  safer_path_templates: []
"""

ACTS_TEMPLATE = """\
# Project Acts (FRAME: A) — Generated by Haxaml

current_phase: ""

active_task:
  name: ""
  description: ""

completed_tasks: []
blocked_tasks: []
decisions: []
unresolved_dependencies: []
runs: []
sessions: []
verifications: []

archive:
  path: ".haxaml/archive/acts-history.yaml"
  archive_mode: manual
  last_archived_at: ""
  archived_counts:
    runs: 0
    sessions: 0
    verifications: 0
  hot_limits:
    runs: 5
    sessions: 5
    verifications: 5

context_compaction:
  sessions_started: 0
  full_reads_completed: 0
  default_pack: balanced
  last_pack_tokens: 0

expect_sync:
  required: false
  pending_run_id: ""
  pending_task: ""
  pending_result: ""
  pending_recorded_at: ""
  last_synced_run_id: ""
  last_synced_at: ""
  last_sync_status: ""

lifecycle_contract:
  phase: idle
  required_next:
    - haxaml_about
  active_session_id: ""
  active_task: ""
  last_tool: ""
  last_verification_id: ""
  last_verification_verdict: ""
  last_record_run_id: ""
  last_record_result: ""
  updated_at: ""
"""

EXPECT_TEMPLATE = """\
# Project Expect (FRAME: E) — Generated by Haxaml

planning:
  goal: "Complete scoped tasks with governed verification."
  strategy: "Iterative small runs with validation before record."
  estimated_runs: 1
  project_size: small
  map_required: false
  map_reason: "Map is optional by default for a new scaffold."

map_policy:
  small_project_max_runs: 5
  medium_project_max_runs: 12
  module_threshold: 10
  cross_impact_touch_threshold: 3
  cross_impact_run_threshold: 2
  dependency_fanout_threshold: 3
  impact_check_threshold: 3
  shared_integration_module_threshold: 2
  require_map_when:
    - "Module count exceeds policy threshold."
  agent_instruction: "Read map.yaml when map_required is true or when task impact crosses module boundaries."

phases:
  - name: "Phase 1"
    status: active
    run_range: "1-1"
    target_runs: 1
    description: "Bootstrap and execute the first governed task."
    done_when: "A scoped task is verified and recorded."

runbook:
  - run: 1
    phase: "Phase 1"
    status: active
    goal: "Execute one scoped task safely."
    outcome: "Task progress is verified and recorded."
    depends_on: []
    touches:
      - "scoped files only"
    requires:
      - "Clear task statement"
    uses_map: false
    verify:
      - "Run tests or validation relevant to touched behavior."
    done_when: "Verification passes and session is recorded."

upcoming:
  - task: "Define the next scoped task"
    priority: critical
    phase: "Phase 1"
    description: "Prepare context, execute, verify, and record."

milestones:
  - name: "First governed run complete"
    status: pending
    criteria: "At least one run is verified and recorded without unresolved blockers."

open_questions: []
"""


def render_frame_templates(*, mode: str | None = None, include_origin: bool = False) -> dict[str, str]:
    """Return the canonical FRAME scaffold text."""
    facts = FACTS_TEMPLATE.rstrip()
    if include_origin and mode:
        facts += f"\n\norigin:\n  mode: {mode}\n  managed_by: haxaml-setup\n"
    return {
        "facts.yaml": facts + "\n",
        "rules.yaml": RULES_TEMPLATE.replace("__HAXAML_VERSION__", get_version()),
        "acts.yaml": ACTS_TEMPLATE,
        "expect.yaml": EXPECT_TEMPLATE,
    }


def write_missing_frame_files(project_dir: Path, *, mode: str | None = None, include_origin: bool = False) -> list[Path]:
    """Write missing FRAME scaffold files and return the created paths."""
    created: list[Path] = []
    for filename, content in render_frame_templates(mode=mode, include_origin=include_origin).items():
        path = frame_path(project_dir, filename)
        if path.exists():
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        created.append(path)
    return created
