"""FRAME → Markdown export engine.

Converts FRAME files (facts/rules/acts/map/expect) into agent-specific
Markdown files that AI coding assistants natively understand.

Supported agents:
- claude   → CLAUDE.md
- windsurf → .windsurf/rules/haxaml.md
- copilot  → .github/copilot-instructions.md
- codex    → AGENTS.md
- cursor   → .cursor/rules/haxaml.mdc
- gemini   → GEMINI.md
- generic  → HAXAML.md
"""

from pathlib import Path
from typing import Any, Optional

import yaml

from haxaml.paths import resolve_frame_file


AGENT_CONFIGS = {
    "claude": {
        "filename": "CLAUDE.md",
        "title": "CLAUDE.md",
        "description": "Project governance for Claude Code / Claude AI",
        "style": "imperative",
    },
    "windsurf": {
        "filename": ".windsurf/rules/haxaml.md",
        "title": "FRAME Governance via Haxaml",
        "description": "Always-on workspace rule for Windsurf / Cascade",
        "style": "imperative",
    },
    "copilot": {
        "filename": ".github/copilot-instructions.md",
        "title": "Copilot Instructions",
        "description": "Project governance for GitHub Copilot",
        "style": "instructional",
    },
    "codex": {
        "filename": "AGENTS.md",
        "title": "AGENTS.md",
        "description": "Project governance for OpenAI Codex CLI",
        "style": "imperative",
    },
    "cursor": {
        "filename": ".cursor/rules/haxaml.mdc",
        "title": "Haxaml Project Governance",
        "description": "Project governance generated by Haxaml from FRAME",
        "style": "imperative",
    },
    "gemini": {
        "filename": "GEMINI.md",
        "title": "GEMINI.md",
        "description": "Project context for Gemini CLI",
        "style": "imperative",
    },
    "generic": {
        "filename": "HAXAML.md",
        "title": "Project Governance (FRAME via Haxaml)",
        "description": "Universal governance file for any AI agent",
        "style": "descriptive",
    },
}


DEFAULT_EXAMPLE_POLICY = {
    "max_examples": 4,
    "max_input_chars": 320,
    "max_output_chars": 420,
    "max_total_chars": 2800,
    "derived_from_acts_max": 4,
    "ordering": "explicit_then_derived",
    "fallback_when_empty": "render_notice",
}


def _load_yaml_safe(path: Path) -> Optional[dict]:
    """Load a YAML file if it exists, return None otherwise."""
    if not path.exists():
        return None
    with open(path) as f:
        return yaml.safe_load(f) or {}


def _resolve_frame_file(project: Path, new_name: str, old_name: str) -> Optional[Path]:
    """Resolve FRAME filename with backward compat."""
    return resolve_frame_file(project, new_name, old_name)


def load_frame(project_dir: str) -> dict:
    """Load all FRAME files from a project directory.

    Returns a dict with keys: facts, rules, acts, map, expect.
    Missing files are None.
    """
    p = Path(project_dir)

    facts_path = _resolve_frame_file(p, "facts.yaml", "brain.yaml")
    rules_path = _resolve_frame_file(p, "rules.yaml", "mind.yaml")
    acts_path = _resolve_frame_file(p, "acts.yaml", "state.yaml")
    map_path = resolve_frame_file(p, "map.yaml")
    expect_path = resolve_frame_file(p, "expect.yaml")

    return {
        "facts": _load_yaml_safe(facts_path) if facts_path else None,
        "rules": _load_yaml_safe(rules_path) if rules_path else None,
        "acts": _load_yaml_safe(acts_path) if acts_path else None,
        "map": _load_yaml_safe(map_path) if map_path else None,
        "expect": _load_yaml_safe(expect_path) if expect_path else None,
    }


def _section(title: str, content: str) -> str:
    """Format a section with title and content."""
    return f"## {title}\n\n{content}"


def _list_items(items: list, prefix: str = "-") -> str:
    """Format a list of items."""
    if not items:
        return "_None defined._"
    return "\n".join(f"{prefix} {item}" for item in items)


def _render_facts(facts: dict, style: str) -> str:
    """Render facts.yaml into markdown."""
    lines = []

    identity = facts.get("identity", {})
    lines.append(f"**Project:** {identity.get('name', 'unknown')}")
    lines.append(f"**Version:** {identity.get('version', '?')}")
    if identity.get("description"):
        lines.append(f"**Description:** {identity['description']}")

    goal = facts.get("goal", {})
    lines.append(f"\n**Purpose:** {goal.get('purpose', 'not defined')}")
    if goal.get("scope"):
        lines.append(f"**Scope:** {goal['scope']}")
    if goal.get("out_of_scope"):
        lines.append(f"**Out of scope:** {goal['out_of_scope']}")

    stack = facts.get("stack", {})
    if stack:
        stack_parts = [f"{k}: {v}" for k, v in stack.items() if v]
        lines.append(f"\n**Stack:** {', '.join(stack_parts)}")

    arch = facts.get("architecture", {})
    if arch:
        lines.append(f"**Architecture:** {arch.get('pattern', '?')} — {arch.get('reasoning', '')}")

    db = facts.get("database", {})
    if db:
        lines.append(f"**Database:** {db.get('type', '?')} ({db.get('connection', '?')})")

    constraints = facts.get("constraints", [])
    if constraints:
        lines.append("\n**Constraints:**")
        for c in constraints:
            lines.append(f"- {c}")

    criteria = facts.get("success_criteria", [])
    if criteria:
        lines.append("\n**Success Criteria:**")
        for c in criteria:
            lines.append(f"- {c}")

    features = facts.get("features", [])
    if features:
        lines.append("\n**Features:**")
        for f in features:
            if isinstance(f, dict):
                status = f.get("status", "?")
                lines.append(f"- [{status}] {f.get('name', '?')}: {f.get('description', '')}")
            else:
                lines.append(f"- {f}")

    return "\n".join(lines)


def _render_rules(rules: dict, style: str) -> str:
    """Render rules.yaml into markdown."""
    lines = []

    # Before task
    before = rules.get("before_task", {})
    read_first = before.get("read_first", [])
    if read_first:
        if style == "imperative":
            lines.append("**Before any task, you MUST read:**")
        else:
            lines.append("**Read first:**")
        for r in read_first:
            lines.append(f"- {r}")

    checks = before.get("check", [])
    if checks:
        lines.append("\n**Pre-task checklist:**")
        for c in checks:
            lines.append(f"- [ ] {c}")

    # Forbidden
    forbidden = rules.get("forbidden", [])
    if forbidden:
        if style == "imperative":
            lines.append("\n**NEVER do the following:**")
        else:
            lines.append("\n**Forbidden actions:**")
        for f in forbidden:
            lines.append(f"- ❌ {f}")

    # Boundaries
    boundaries = rules.get("boundaries", {})
    boundary_rules = boundaries.get("rules", [])
    if boundary_rules:
        lines.append("\n**Boundary rules:**")
        for r in boundary_rules:
            lines.append(f"- {r}")

    # While coding
    while_coding = rules.get("while_coding", {})
    wc_rules = while_coding.get("rules", [])
    if wc_rules:
        lines.append("\n**While coding:**")
        for r in wc_rules:
            lines.append(f"- {r}")

    # After task
    after = rules.get("after_task", {})
    update = after.get("update", [])
    report = after.get("report", [])
    if update or report:
        lines.append("\n**After completing a task:**")
        for u in update:
            lines.append(f"- Update: {u}")
        for r in report:
            lines.append(f"- Report: {r}")

    # Escalation
    escalation = rules.get("escalation", {})
    ask_user = escalation.get("ask_first", escalation.get("ask_user", []))
    if ask_user:
        lines.append("\n**Ask the user before:**")
        for a in ask_user:
            lines.append(f"- {a}")

    return "\n".join(lines)


def _agent_profile(rules: Optional[dict]) -> dict:
    if not isinstance(rules, dict):
        return {}
    profile = rules.get("agent_profile", {})
    return profile if isinstance(profile, dict) else {}


def _normalize_text(value: Any) -> str:
    if value is None:
        return ""
    text = str(value).replace("\r\n", "\n")
    return "\n".join(" ".join(line.split()) for line in text.split("\n")).strip()


def _truncate_text(text: str, max_chars: int) -> tuple[str, bool]:
    if len(text) <= max_chars:
        return text, False
    if max_chars <= 1:
        return "…", True
    return text[: max_chars - 1].rstrip() + "…", True


def _safe_int(value: Any, default: int) -> int:
    return value if isinstance(value, int) and value >= 0 else default


def _example_policy(profile: dict) -> dict:
    policy = dict(DEFAULT_EXAMPLE_POLICY)
    incoming = profile.get("example_policy", {})
    if isinstance(incoming, dict):
        for key, default in DEFAULT_EXAMPLE_POLICY.items():
            if key not in incoming:
                continue
            if isinstance(default, int):
                policy[key] = _safe_int(incoming[key], default)
            elif isinstance(default, str) and isinstance(incoming[key], str):
                policy[key] = incoming[key]
    return policy


def _render_codex_persona(rules: Optional[dict]) -> str:
    profile = _agent_profile(rules)
    persona = profile.get("persona", {})
    if not isinstance(persona, dict):
        persona = {}

    role = _normalize_text(
        persona.get(
            "role",
            "Deterministic software engineer operating under FRAME governance and explicit project constraints.",
        )
    )
    tone = persona.get("tone", [])
    constraints = persona.get("constraints", [])

    tone_items = tone if isinstance(tone, list) and tone else [
        "Direct, concise, and factual communication.",
        "Prioritize practical implementation and verification steps.",
    ]
    constraint_items = constraints if isinstance(constraints, list) and constraints else [
        "Keep generated outputs deterministic from FRAME input files.",
        "Avoid unverified claims; report checks and residual risks.",
    ]

    lines = [f"**Role:** {role}", "\n**Tone:**"]
    lines.extend(f"- {_normalize_text(item)}" for item in tone_items if _normalize_text(item))
    lines.append("\n**Operating constraints:**")
    lines.extend(f"- {_normalize_text(item)}" for item in constraint_items if _normalize_text(item))
    return "\n".join(lines)


def _render_codex_reasoning_policy(rules: Optional[dict]) -> str:
    profile = _agent_profile(rules)
    reasoning = profile.get("reasoning_policy", {})
    output_contract = profile.get("output_contract", {})
    if not isinstance(reasoning, dict):
        reasoning = {}
    if not isinstance(output_contract, dict):
        output_contract = {}

    private_reasoning = _normalize_text(
        reasoning.get(
            "private_reasoning",
            "Keep private reasoning internal. Do not expose internal deliberation transcripts.",
        )
    )
    public_rationale = _normalize_text(
        reasoning.get(
            "public_rationale",
            "Provide concise rationale tied to file changes, tests, and concrete evidence.",
        )
    )
    checklist = reasoning.get("checklist", [])
    checklist_items = checklist if isinstance(checklist, list) and checklist else [
        "State what changed.",
        "List tests/checks run.",
        "State remaining risks or follow-ups.",
    ]

    required_sections = output_contract.get("required_sections", [])
    required_items = (
        required_sections
        if isinstance(required_sections, list) and required_sections
        else ["Summary", "Changes", "Verification", "Risks"]
    )
    format_notes = output_contract.get("format_notes", [])
    format_items = format_notes if isinstance(format_notes, list) else []

    lines = [
        f"**Private reasoning policy:** {private_reasoning}",
        f"**Public rationale policy:** {public_rationale}",
        "\n**Response checklist:**",
    ]
    lines.extend(f"- {_normalize_text(item)}" for item in checklist_items if _normalize_text(item))
    lines.append("\n**Output contract:**")
    lines.extend(f"- Required section: `{_normalize_text(item)}`" for item in required_items if _normalize_text(item))
    for note in format_items:
        normalized = _normalize_text(note)
        if normalized:
            lines.append(f"- Format note: {normalized}")

    return "\n".join(lines)


def _explicit_examples(profile: dict) -> list[dict]:
    explicit = []
    raw = profile.get("few_shot_examples", [])
    if not isinstance(raw, list):
        return explicit
    for item in raw:
        if not isinstance(item, dict):
            continue
        input_text = _normalize_text(item.get("input"))
        output_text = _normalize_text(item.get("output"))
        if not input_text or not output_text:
            continue
        explicit.append(
            {
                "source": "explicit",
                "title": _normalize_text(item.get("title")) or "Explicit example",
                "input": input_text,
                "output": output_text,
            }
        )
    return explicit


def _derived_examples_from_acts(acts: Optional[dict]) -> list[dict]:
    if not isinstance(acts, dict):
        return []

    derived = []

    decisions = acts.get("decisions", [])
    if isinstance(decisions, list):
        for item in reversed(decisions):
            if not isinstance(item, dict):
                continue
            decision = _normalize_text(item.get("decision"))
            reasoning = _normalize_text(item.get("reasoning"))
            if not decision or not reasoning:
                continue
            derived.append(
                {
                    "source": "derived",
                    "title": f"Decision pattern: {decision}",
                    "input": f"User asks for a decision: {decision}",
                    "output": f"Decision: {decision}\nRationale: {reasoning}",
                }
            )

    completed_tasks = acts.get("completed_tasks", [])
    if isinstance(completed_tasks, list):
        for item in reversed(completed_tasks):
            if not isinstance(item, dict):
                continue
            name = _normalize_text(item.get("name"))
            summary = _normalize_text(item.get("summary"))
            result = _normalize_text(item.get("result")) or "unknown"
            if not name or not summary:
                continue
            derived.append(
                {
                    "source": "derived",
                    "title": f"Completion pattern: {name}",
                    "input": f"User asks for implementation status on '{name}'.",
                    "output": f"Result: {result}\nSummary: {summary}",
                }
            )

    return derived


def _select_examples(rules: Optional[dict], acts: Optional[dict]) -> tuple[list[dict], list[str]]:
    profile = _agent_profile(rules)
    policy = _example_policy(profile)
    max_examples = max(1, policy["max_examples"])
    max_input_chars = max(64, policy["max_input_chars"])
    max_output_chars = max(64, policy["max_output_chars"])
    max_total_chars = max(256, policy["max_total_chars"])
    derived_cap = policy["derived_from_acts_max"]

    explicit = _explicit_examples(profile)
    derived = _derived_examples_from_acts(acts)[:derived_cap]
    pool = explicit + derived

    selected = []
    total_chars = 0
    truncated_fields = 0
    omitted_for_budget = 0

    for item in pool:
        if len(selected) >= max_examples:
            break

        title, title_trunc = _truncate_text(_normalize_text(item.get("title", "")), 120)
        input_text, input_trunc = _truncate_text(_normalize_text(item.get("input", "")), max_input_chars)
        output_text, output_trunc = _truncate_text(_normalize_text(item.get("output", "")), max_output_chars)

        if title_trunc or input_trunc or output_trunc:
            truncated_fields += int(title_trunc) + int(input_trunc) + int(output_trunc)

        candidate_size = len(title) + len(input_text) + len(output_text)
        if selected and total_chars + candidate_size > max_total_chars:
            omitted_for_budget += 1
            break

        selected.append(
            {
                "source": item["source"],
                "title": title,
                "input": input_text,
                "output": output_text,
            }
        )
        total_chars += candidate_size

    notes = [
        "Source precedence: explicit `rules.agent_profile.few_shot_examples` first, then derived snippets from recent `acts` decisions/completed tasks."
    ]
    if len(pool) > len(selected):
        notes.append(
            f"Compaction: showing {len(selected)} of {len(pool)} candidate examples (max_examples={max_examples})."
        )
    if omitted_for_budget:
        notes.append(
            f"Budget guard: stopped after deterministic prefix because max_total_chars={max_total_chars} was reached."
        )
    if truncated_fields:
        notes.append(
            f"Truncation: compacted {truncated_fields} field(s) to per-example limits "
            f"(input={max_input_chars}, output={max_output_chars})."
        )
    return selected, notes


def _render_codex_few_shot_examples(rules: Optional[dict], acts: Optional[dict]) -> str:
    profile = _agent_profile(rules)
    policy = _example_policy(profile)
    examples, notes = _select_examples(rules, acts)

    if not examples:
        if policy.get("fallback_when_empty") == "omit_section":
            return ""
        return (
            "No few-shot examples available.\n\n"
            "Add `rules.agent_profile.few_shot_examples` or keep recent decisions/completed-task "
            "summaries in `.haxaml/acts.yaml` to generate deterministic examples."
        )

    lines = [f"- {note}" for note in notes]
    for idx, example in enumerate(examples, start=1):
        lines.append(f"\n### Example {idx} ({example['source']})")
        lines.append(f"**Input:** {example['input']}")
        lines.append("**Output:**")
        lines.append(example["output"])
    return "\n".join(lines)


def _render_acts(acts: dict, style: str) -> str:
    """Render acts.yaml into markdown."""
    lines = []

    lines.append(f"**Current Phase:** {acts.get('current_phase', 'unknown')}")

    task = acts.get("active_task", {})
    if task:
        lines.append(f"**Active Task:** {task.get('name', 'none')}")
        if task.get("description"):
            lines.append(f"  _{task['description']}_")

    blocked = acts.get("blocked_tasks", [])
    if blocked:
        lines.append("\n**Blocked:**")
        for b in blocked:
            if isinstance(b, dict):
                lines.append(f"- {b.get('name', '?')}: {b.get('reason', '?')}")
            else:
                lines.append(f"- {b}")

    decisions = acts.get("decisions", [])
    if decisions:
        recent = decisions[-5:]
        lines.append(f"\n**Recent Decisions ({len(recent)} of {len(decisions)}):**")
        for d in recent:
            if isinstance(d, dict):
                lines.append(f"- {d.get('decision', '?')} — _{d.get('reasoning', '')}_")
            else:
                lines.append(f"- {d}")

    completed = acts.get("completed_tasks", [])
    if completed:
        lines.append(f"\n**Completed Tasks:** {len(completed)}")

    return "\n".join(lines)


def _render_expect(expect: dict, style: str) -> str:
    """Render expect.yaml into markdown."""
    lines = []

    planning = expect.get("planning", {})
    if planning:
        if planning.get("goal"):
            lines.append(f"**Goal:** {planning['goal']}")
        if planning.get("estimated_runs"):
            lines.append(
                f"**Expected runs:** {planning['estimated_runs']} "
                f"({planning.get('project_size', 'unknown')})"
            )
        if "map_required" in planning:
            state = "required" if planning.get("map_required") else "not required yet"
            lines.append(f"**Map:** {state}")
            if planning.get("map_reason"):
                lines.append(f"  _{planning['map_reason']}_")

    phases = expect.get("phases", [])
    active = [p for p in phases if p.get("status") == "active"]
    if active:
        phase = active[0]
        lines.append(f"**Active Phase:** {phase['name']}")
        if phase.get("done_when"):
            lines.append(f"  _Done when: {phase['done_when']}_")

    upcoming = expect.get("upcoming", [])
    if upcoming:
        lines.append("\n**Upcoming Tasks:**")
        for t in upcoming[:8]:
            pri = t.get("priority", "?")
            lines.append(f"- [{pri}] {t.get('task', '?')}")

    runbook = expect.get("runbook", [])
    visible_runs = [r for r in runbook if r.get("status") in ("active", "planned", "blocked")]
    if visible_runs:
        lines.append("\n**Runbook:**")
        for r in visible_runs[:6]:
            lines.append(f"- Run {r.get('run', '?')} [{r.get('status', '?')}]: {r.get('goal', '?')}")
            if r.get("outcome"):
                lines.append(f"  Outcome: {r['outcome']}")
            if r.get("uses_map"):
                lines.append("  Uses map.yaml: yes")

    map_policy = expect.get("map_policy", {})
    if map_policy.get("agent_instruction"):
        lines.append(f"\n**Map policy:** {map_policy['agent_instruction']}")

    questions = expect.get("open_questions", [])
    if questions:
        blocking_q = [q for q in questions if q.get("blocking")]
        if blocking_q:
            lines.append("\n**⚠ Blocking Questions:**")
            for q in blocking_q:
                lines.append(f"- {q['question']}")

    milestones = expect.get("milestones", [])
    if milestones:
        lines.append("\n**Milestones:**")
        for m in milestones:
            if isinstance(m, dict):
                status = "✓" if m.get("done") else "○"
                lines.append(f"- {status} {m.get('name', '?')}")
            else:
                lines.append(f"- {m}")

    return "\n".join(lines)


def _render_map(map_data: dict, style: str) -> str:
    """Render map.yaml into markdown."""
    lines = []

    modules = map_data.get("modules", [])
    if modules:
        lines.append("| Module | Purpose | Files |")
        lines.append("|--------|---------|-------|")
        for m in modules:
            files = ", ".join(m.get("files", [])[:3])
            if len(m.get("files", [])) > 3:
                files += "..."
            lines.append(f"| {m['name']} | {m.get('purpose', '')} | {files} |")

    deps = map_data.get("dependencies", [])
    if deps:
        lines.append("\n**Dependencies:**")
        for d in deps:
            lines.append(f"- {d['from']} → {d['to']}" + (f" ({d['reason']})" if d.get("reason") else ""))

    impact = map_data.get("impact", [])
    if impact:
        lines.append("\n**Impact Rules:**")
        for i in impact:
            checks = ", ".join(i.get("check", []))
            lines.append(f"- When `{i['when']}` changes → check: {checks}")

    return "\n".join(lines)


def _agent_header(config: dict, agent: str = "generic") -> str:
    """Generate agent-specific header."""
    if agent == "cursor":
        # MDC frontmatter for Cursor project rules (.mdc format)
        return (
            "---\n"
            f"description: {config['description']}\n"
            "alwaysApply: true\n"
            "---\n\n"
            f"# {config['title']}\n\n"
            "> Generated by Haxaml from FRAME. Do not edit manually — regenerate with `haxaml export`.\n"
        )
    if agent == "windsurf":
        return (
            "---\n"
            "trigger: always_on\n"
            f"description: {config['description']}\n"
            "---\n\n"
            f"# {config['title']}\n\n"
            "> Generated by Haxaml from FRAME. Do not edit manually — regenerate with `haxaml export`.\n"
        )
    return f"# {config['title']}\n\n> {config['description']}\n> Generated by Haxaml from FRAME. Do not edit manually — regenerate with `haxaml export`.\n"


def _agent_footer(agent: str) -> str:
    """Generate agent-specific footer."""
    tips = {
        "claude": (
            "\n---\n\n"
            "## How to Use This File\n\n"
            "Claude Code reads CLAUDE.md automatically from your project root.\n"
            "It provides project context, rules, and state at the start of every conversation.\n\n"
            "Regenerate after changes: `haxaml export --agent claude`\n"
        ),
        "windsurf": (
            "\n---\n\n"
            "## How to Use This File\n\n"
            "Windsurf/Cascade reads workspace rules from `.windsurf/rules/*.md`.\n"
            "This rule uses `trigger: always_on`, so it is included in Cascade context.\n\n"
            "Regenerate after changes: `haxaml export --agent windsurf`\n"
        ),
        "copilot": (
            "\n---\n\n"
            "## How to Use This File\n\n"
            "GitHub Copilot reads .github/copilot-instructions.md automatically.\n"
            "It guides Copilot's suggestions and completions.\n\n"
            "Regenerate after changes: `haxaml export --agent copilot`\n"
        ),
        "codex": (
            "\n---\n\n"
            "## How to Use This File\n\n"
            "Codex CLI reads AGENTS.md from your project root automatically.\n"
            "It provides project governance for every task.\n\n"
            "Nested AGENTS.md files in subdirectories provide directory-specific instructions.\n\n"
            "Regenerate after changes: `haxaml export --agent codex`\n"
        ),
        "cursor": (
            "\n---\n\n"
            "## How to Use This File\n\n"
            "Cursor reads project rules from `.cursor/rules/` as `.mdc` files.\n"
            "This rule is set to `alwaysApply: true` — it applies to every conversation.\n\n"
            "Rule precedence: Team Rules → Project Rules → User Rules.\n\n"
            "Regenerate after changes: `haxaml export --agent cursor`\n"
        ),
        "gemini": (
            "\n---\n\n"
            "## How to Use This File\n\n"
            "Gemini CLI loads `GEMINI.md` context files from the workspace hierarchy.\n"
            "This file gives Gemini project facts, rules, current state, map guidance, and expected runs.\n\n"
            "Regenerate after changes: `haxaml export --agent gemini`\n"
        ),
        "generic": (
            "\n---\n\n"
            "## How to Use This File\n\n"
            "This is a universal governance file generated by Haxaml from FRAME.\n"
            "Paste it into any AI agent's system prompt or project instructions.\n\n"
            "Regenerate after changes: `haxaml export --agent generic`\n"
        ),
    }
    return tips.get(agent, tips["generic"])


def export_frame_to_markdown(project_dir: str, agent: str = "generic") -> str:
    """Export FRAME files to agent-specific markdown.

    Args:
        project_dir: Path to the project directory.
        agent: Target agent (claude, windsurf, copilot, codex, cursor, gemini, generic).

    Returns:
        Markdown string ready to write to file.
    """
    if agent not in AGENT_CONFIGS:
        raise ValueError(f"Unknown agent: {agent}. Supported: {', '.join(AGENT_CONFIGS)}")

    config = AGENT_CONFIGS[agent]
    style = config["style"]
    frame = load_frame(project_dir)
    parts = []

    # Header
    parts.append(_agent_header(config, agent))

    # Facts
    if frame["facts"]:
        parts.append(_section("Project Facts", _render_facts(frame["facts"], style)))

    if agent == "codex":
        parts.append(_section("Agent Persona", _render_codex_persona(frame["rules"])))
        parts.append(
            _section(
                "Reasoning & Response Policy",
                _render_codex_reasoning_policy(frame["rules"]),
            )
        )
        few_shot = _render_codex_few_shot_examples(frame["rules"], frame["acts"])
        if few_shot:
            parts.append(_section("Few-Shot Examples", few_shot))

    # Rules
    if frame["rules"]:
        parts.append(_section("Rules & Conventions", _render_rules(frame["rules"], style)))

    # Current State
    if frame["acts"]:
        parts.append(_section("Current State", _render_acts(frame["acts"], style)))

    # Module Map
    if frame["map"]:
        parts.append(_section("Module Map", _render_map(frame["map"], style)))

    # Plan
    if frame["expect"]:
        parts.append(_section("What's Expected Next", _render_expect(frame["expect"], style)))

    # Footer
    parts.append(_agent_footer(agent))

    return "\n\n".join(parts)


def export_to_file(project_dir: str, agent: str = "generic",
                   output_path: Optional[str] = None) -> str:
    """Export FRAME to agent-specific markdown file.

    Args:
        project_dir: Path to the project directory.
        agent: Target agent.
        output_path: Override output path. If None, uses default for the agent.

    Returns:
        The path of the written file.
    """
    config = AGENT_CONFIGS[agent]
    content = export_frame_to_markdown(project_dir, agent)

    if output_path is None:
        output_path = str(Path(project_dir) / config["filename"])

    # Ensure parent directory exists
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        f.write(content)

    return output_path


def list_agents() -> list[dict]:
    """List all supported agents with their output filenames."""
    return [
        {"name": name, "filename": cfg["filename"], "description": cfg["description"]}
        for name, cfg in AGENT_CONFIGS.items()
    ]
