"""FRAME → Markdown export engine.

Converts FRAME files (facts/rules/acts/map/expect) into agent-specific
Markdown files that AI coding assistants natively understand.

Supported agents:
- claude   → CLAUDE.md
- windsurf → .windsurf/rules/haxaml.md
- copilot  → .github/copilot-instructions.md
- codex    → haxaml-agents.md (or AGENTS.md when explicitly requested)
- cursor   → .cursor/rules/haxaml.mdc
- gemini   → GEMINI.md
- generic  → HAXAML.md

v0.6 PromptRecipe pipeline
--------------------------
All exports go through:
  FrameModel.load() → build_recipe() → _render_recipe() → Markdown

PromptRecipe is the normalised intermediate representation.
Downstream rendering helpers (_render_facts, _render_rules, etc.) operate
on PromptRecipe.sections[], not the raw FRAME dicts directly.  This keeps
rendering deterministic and testable without a filesystem.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from haxaml.export_profiles import (
    agent_profile as _agent_profile,
    render_agent_few_shot_examples as _render_agent_few_shot_examples,
    render_agent_persona as _render_agent_persona,
    render_agent_reasoning_policy as _render_agent_reasoning_policy,
)
from haxaml.frame_model import FrameModel
from haxaml.paths import resolve_frame_file
from haxaml.yaml_utils import load_yaml_if_exists


GENERATED_MARKER = "Generated by Haxaml from FRAME"


AGENT_CONFIGS = {
    "claude": {
        "filename": "CLAUDE.md",
        "title": "CLAUDE.md",
        "description": "Project governance for Claude Code / Claude AI",
        "style": "imperative",
    },
    "windsurf": {
        "filename": ".windsurf/rules/haxaml.md",
        "title": "FRAME Governance via Haxaml",
        "description": "Always-on workspace rule for Windsurf / Cascade",
        "style": "imperative",
    },
    "copilot": {
        "filename": ".github/copilot-instructions.md",
        "title": "Copilot Instructions",
        "description": "Project governance for GitHub Copilot",
        "style": "instructional",
    },
    "codex": {
        "filename": "haxaml-agents.md",
        "native_filename": "AGENTS.md",
        "title": "Haxaml Agent Context (Codex)",
        "description": "Project governance for OpenAI Codex CLI",
        "style": "imperative",
    },
    "cursor": {
        "filename": ".cursor/rules/haxaml.mdc",
        "title": "Haxaml Project Governance",
        "description": "Project governance generated by Haxaml from FRAME",
        "style": "imperative",
    },
    "gemini": {
        "filename": "GEMINI.md",
        "title": "GEMINI.md",
        "description": "Project context for Gemini CLI",
        "style": "imperative",
    },
    "generic": {
        "filename": "HAXAML.md",
        "title": "Haxaml Project Context",
        "description": "Unified project context generated from FRAME",
        "style": "descriptive",
    },
}


# ---------------------------------------------------------------------------
# PromptRecipe — normalised intermediate representation for export pipeline
# ---------------------------------------------------------------------------

@dataclass
class RecipeSection:
    """One rendered section of the export output."""
    key: str
    title: str
    content: str
    included: bool = True


@dataclass
class PromptRecipe:
    """Normalised export recipe produced from a FrameModel.

    Sections are ordered and keyed.  Renderers downstream consume sections
    directly; callers can inspect, filter, or override sections before
    handing off to _render_recipe().
    """
    agent: str
    style: str
    sections: list[RecipeSection] = field(default_factory=list)
    header: str = ""
    footer: str = ""

    def get(self, key: str) -> Optional[RecipeSection]:
        for s in self.sections:
            if s.key == key:
                return s
        return None

    def exclude(self, *keys: str) -> "PromptRecipe":
        """Return a copy of this recipe with the named sections excluded."""
        import copy
        r = copy.copy(self)
        r.sections = [
            s for s in self.sections if s.key not in keys
        ]
        return r


def build_recipe(frame: FrameModel, agent: str = "generic") -> PromptRecipe:
    """Build a PromptRecipe from a FrameModel.

    All export rendering is deterministic from the recipe, so golden tests
    can compare recipe sections without writing files.
    """
    if agent not in AGENT_CONFIGS:
        raise ValueError(f"Unknown agent: {agent}. Supported: {', '.join(AGENT_CONFIGS)}")

    config = AGENT_CONFIGS[agent]
    style = config["style"]

    sections: list[RecipeSection] = []

    # The recipe is assembled in the same conceptual order the final prompt
    # should teach the agent: facts first, then profile/rules, then current
    # state and expectations.
    if frame.has_facts():
        sections.append(RecipeSection(
            key="facts",
            title="Project Facts",
            content=_render_facts(frame.facts or {}, style),
        ))

    profile = _agent_profile(frame.rules)
    if profile:
        sections.append(RecipeSection(
            key="persona",
            title="Working Profile",
            content=_render_agent_persona(frame.rules),
        ))
        sections.append(RecipeSection(
            key="reasoning",
            title="Reasoning & Response Style",
            content=_render_agent_reasoning_policy(frame.rules),
        ))
        few_shot = _render_agent_few_shot_examples(frame.rules, frame.acts)
        if few_shot:
            sections.append(RecipeSection(
                key="examples",
                title="Reference Examples",
                content=few_shot,
            ))

    if frame.has_rules():
        sections.append(RecipeSection(
            key="rules",
            title="Rules & Conventions",
            content=_render_rules(frame.rules or {}, style),
        ))

    if frame.has_acts():
        sections.append(RecipeSection(
            key="acts",
            title="Current State",
            content=_render_acts(frame.acts or {}, style),
        ))

    if frame.has_map():
        sections.append(RecipeSection(
            key="map",
            title="Module Map",
            content=_render_map(frame.map or {}, style),
        ))

    if frame.has_expect():
        sections.append(RecipeSection(
            key="expect",
            title="What's Expected Next",
            content=_render_expect(frame.expect or {}, style),
        ))

    recipe = PromptRecipe(
        agent=agent,
        style=style,
        sections=sections,
        header=_agent_header(config, agent),
        footer=_agent_footer(agent),
    )
    return recipe


def _render_recipe(recipe: PromptRecipe) -> str:
    """Render a PromptRecipe to a Markdown string."""
    parts = [recipe.header]
    for section in recipe.sections:
        if section.included and section.content.strip():
            parts.append(_section(section.title, section.content))
    parts.append(recipe.footer)
    return "\n\n".join(parts)


def _load_yaml_safe(path: Path) -> Optional[dict]:
    """Load a YAML file if it exists, return None otherwise."""
    return load_yaml_if_exists(path)


def _section(title: str, content: str) -> str:
    """Format a section with title and content."""
    return f"## {title}\n\n{content}"


def _list_items(items: list, prefix: str = "-") -> str:
    """Format a list of items."""
    if not items:
        return "_None defined._"
    return "\n".join(f"{prefix} {item}" for item in items)


def _render_facts(facts: dict, style: str) -> str:
    """Render facts.yaml into markdown."""
    lines = []

    identity = facts.get("identity", {})
    name = identity.get("name", "unknown")
    version = identity.get("version", "?")
    lines.append(f"Project: {name} (v{version})")
    if identity.get("description"):
        lines.append(identity["description"])

    goal = facts.get("goal", {})
    lines.append("")
    lines.append(f"Purpose: {goal.get('purpose', 'not defined')}")
    if goal.get("scope"):
        lines.append(f"Scope: {goal['scope']}")
    if goal.get("out_of_scope"):
        lines.append("Out of scope:")
        for item in goal["out_of_scope"]:
            lines.append(f"- {item}")

    stack = facts.get("stack", {})
    if stack:
        stack_parts = [f"{k}: {v}" for k, v in stack.items() if v]
        lines.append("")
        lines.append(f"Stack: {', '.join(stack_parts)}")

    arch = facts.get("architecture", {})
    if arch:
        lines.append(f"Architecture: {arch.get('pattern', '?')}")
        if arch.get("reasoning"):
            lines.append(f"Why this shape: {arch.get('reasoning', '').strip()}")

    db = facts.get("database", {})
    if db:
        lines.append(f"Database: {db.get('type', '?')} ({db.get('connection', '?')})")

    constraints = facts.get("constraints", [])
    if constraints:
        lines.append("")
        lines.append("Constraints:")
        for c in constraints:
            lines.append(f"- {c}")

    criteria = facts.get("success_criteria", [])
    if criteria:
        lines.append("")
        lines.append("Success criteria:")
        for c in criteria:
            lines.append(f"- {c}")

    features = facts.get("features", [])
    if features:
        lines.append("")
        lines.append("Features:")
        for f in features:
            if isinstance(f, dict):
                status = f.get("status", "?")
                lines.append(f"- [{status}] {f.get('name', '?')}: {f.get('description', '').strip()}")
            else:
                lines.append(f"- {f}")

    return "\n".join(lines)


def _render_rules(rules: dict, style: str) -> str:
    """Render rules.yaml into markdown."""
    lines = [
        "Use these as operating rules. Keep the work scoped, verifiable, and explicit."
    ]

    before = rules.get("before_task", {})
    read_first = before.get("read_first", [])
    if read_first:
        lines.append("\nBefore starting, read:")
        for r in read_first:
            lines.append(f"- {r}")

    checks = before.get("check", [])
    if checks:
        lines.append("\nPre-task checks:")
        for c in checks:
            lines.append(f"- {c}")

    boundaries = rules.get("boundaries", {})
    boundary_rules = boundaries.get("rules", [])
    if boundary_rules:
        lines.append("\nBoundary rules:")
        for r in boundary_rules:
            lines.append(f"- {r}")

    while_coding = rules.get("while_coding", {})
    wc_constraints = while_coding.get("constraints", [])
    wc_discipline = while_coding.get("discipline", [])
    if wc_constraints or wc_discipline:
        lines.append("\nWhile implementing:")
        for item in wc_constraints:
            lines.append(f"- Constraint: {item}")
        for item in wc_discipline:
            lines.append(f"- Discipline: {item}")

    forbidden = rules.get("forbidden", [])
    if forbidden:
        lines.append("\nNever do this:")
        for f in forbidden:
            lines.append(f"- {f}")

    after = rules.get("after_task", {})
    update = after.get("update", [])
    report = after.get("report", [])
    verify = after.get("verify", [])
    if update or report or verify:
        lines.append("\nWhen the task is done:")
        for u in update:
            lines.append(f"- Update: {u}")
        for r in report:
            lines.append(f"- Report: {r}")
        for v in verify:
            lines.append(f"- Verify: {v}")

    escalation = rules.get("escalation", {})
    ask_user = escalation.get("ask_first", escalation.get("ask_user", []))
    if ask_user:
        lines.append("\nAsk the user first when:")
        for a in ask_user:
            lines.append(f"- {a}")

    return "\n".join(lines)


def _render_acts(acts: dict, style: str) -> str:
    """Render acts.yaml into markdown."""
    lines = []

    lines.append(f"Current phase: {acts.get('current_phase', 'unknown')}")
    lines.append("Use this as the live diary for planning and execution decisions.")

    task = acts.get("active_task", {})
    if task:
        lines.append(f"Active task: {task.get('name', 'none')}")
        if task.get("description"):
            lines.append(f"Task detail: {task['description']}")

    blocked = acts.get("blocked_tasks", [])
    if blocked:
        lines.append("\nBlocked:")
        for b in blocked:
            if isinstance(b, dict):
                lines.append(f"- {b.get('name', '?')}: {b.get('reason', '?')}")
            else:
                lines.append(f"- {b}")

    decisions = acts.get("decisions", [])
    if decisions:
        recent = decisions[-5:]
        lines.append(f"\nRecent decisions ({len(recent)} of {len(decisions)}):")
        for d in recent:
            if isinstance(d, dict):
                lines.append(f"- {d.get('decision', '?')} ({d.get('reasoning', '').strip()})")
            else:
                lines.append(f"- {d}")

    completed = acts.get("completed_tasks", [])
    if completed:
        lines.append(f"\nCompleted tasks total: {len(completed)}")

    return "\n".join(lines)


def _render_expect(expect: dict, style: str) -> str:
    """Render expect.yaml into markdown."""
    lines = []

    lines.append("This is the forward plan from current state to target outcome.")
    planning = expect.get("planning", {})
    if planning:
        if planning.get("goal"):
            lines.append(f"Goal: {planning['goal']}")
        if planning.get("estimated_runs"):
            lines.append(f"Expected runs: {planning['estimated_runs']} ({planning.get('project_size', 'unknown')})")
        if "map_required" in planning:
            state = "required" if planning.get("map_required") else "not required yet"
            lines.append(f"Map: {state}")
            if planning.get("map_reason"):
                lines.append(f"Map reason: {planning['map_reason']}")

    phases = expect.get("phases", [])
    active = [p for p in phases if p.get("status") == "active"]
    if active:
        phase = active[0]
        lines.append(f"Active phase: {phase['name']}")
        if phase.get("done_when"):
            lines.append(f"Phase done when: {phase['done_when']}")

    upcoming = expect.get("upcoming", [])
    if upcoming:
        lines.append("\nUpcoming tasks:")
        for t in upcoming[:8]:
            pri = t.get("priority", "?")
            lines.append(f"- [{pri}] {t.get('task', '?')}")

    runbook = expect.get("runbook", [])
    visible_runs = [r for r in runbook if r.get("status") in ("active", "planned", "blocked")]
    if visible_runs:
        lines.append("\nRunbook:")
        for r in visible_runs[:6]:
            lines.append(f"- Run {r.get('run', '?')} [{r.get('status', '?')}]: {r.get('goal', '?')}")
            if r.get("outcome"):
                lines.append(f"  Outcome: {r['outcome']}")
            if r.get("uses_map"):
                lines.append("  Uses map.yaml: yes")

    map_policy = expect.get("map_policy", {})
    if map_policy.get("agent_instruction"):
        lines.append(f"\nMap policy: {map_policy['agent_instruction']}")

    questions = expect.get("open_questions", [])
    if questions:
        blocking_q = [q for q in questions if q.get("blocking")]
        if blocking_q:
            lines.append("\nBlocking questions:")
            for q in blocking_q:
                lines.append(f"- {q['question']}")

    milestones = expect.get("milestones", [])
    if milestones:
        lines.append("\nMilestones:")
        for m in milestones:
            if isinstance(m, dict):
                status = "✓" if m.get("done") else "○"
                lines.append(f"- {status} {m.get('name', '?')}")
            else:
                lines.append(f"- {m}")

    return "\n".join(lines)


def _render_map(map_data: dict, style: str) -> str:
    """Render map.yaml into markdown."""
    lines = []

    modules = map_data.get("modules", [])
    if modules:
        lines.append("| Module | Purpose | Files |")
        lines.append("|--------|---------|-------|")
        for m in modules:
            files = ", ".join(m.get("files", [])[:3])
            if len(m.get("files", [])) > 3:
                files += "..."
            lines.append(f"| {m['name']} | {m.get('purpose', '')} | {files} |")

    deps = map_data.get("dependencies", [])
    if deps:
        lines.append("\nDependencies:")
        for d in deps:
            lines.append(f"- {d['from']} → {d['to']}" + (f" ({d['reason']})" if d.get("reason") else ""))

    impact = map_data.get("impact", [])
    if impact:
        lines.append("\nImpact rules:")
        for i in impact:
            checks = ", ".join(i.get("check", []))
            lines.append(f"- When `{i['when']}` changes → check: {checks}")

    return "\n".join(lines)


def _agent_header(config: dict, agent: str = "generic") -> str:
    """Generate agent-specific header."""
    if agent == "cursor":
        # MDC frontmatter for Cursor project rules (.mdc format)
        return (
            "---\n"
            f"description: {config['description']}\n"
            "alwaysApply: true\n"
            "---\n\n"
            f"# {config['title']}\n\n"
            f"> {GENERATED_MARKER}. Regenerate with `haxaml export`.\n"
        )
    if agent == "windsurf":
        return (
            "---\n"
            "trigger: always_on\n"
            f"description: {config['description']}\n"
            "---\n\n"
            f"# {config['title']}\n\n"
            f"> {GENERATED_MARKER}. Regenerate with `haxaml export`.\n"
        )
    return (
        f"# {config['title']}\n\n"
        f"{config['description']}\n\n"
        f"> {GENERATED_MARKER}. Regenerate with `haxaml export`.\n"
    )


def _agent_footer(agent: str) -> str:
    """Generate agent-specific footer."""
    tips = {
        "claude": (
            "\n---\n\n"
            "## How to Use This File\n\n"
            "Claude Code reads CLAUDE.md automatically from your project root.\n"
            "It provides project context, rules, and state at the start of every conversation.\n\n"
            "Regenerate after changes: `haxaml export --agent claude`\n"
        ),
        "windsurf": (
            "\n---\n\n"
            "## How to Use This File\n\n"
            "Windsurf/Cascade reads workspace rules from `.windsurf/rules/*.md`.\n"
            "This rule uses `trigger: always_on`, so it is included in Cascade context.\n\n"
            "Regenerate after changes: `haxaml export --agent windsurf`\n"
        ),
        "copilot": (
            "\n---\n\n"
            "## How to Use This File\n\n"
            "GitHub Copilot reads .github/copilot-instructions.md automatically.\n"
            "It guides Copilot's suggestions and completions.\n\n"
            "Regenerate after changes: `haxaml export --agent copilot`\n"
        ),
        "codex": (
            "\n---\n\n"
            "## How to Use This File\n\n"
            "Codex can read this file directly, or you can export with `--override-native` to write `AGENTS.md`.\n"
            "Keep this file concise and action-oriented.\n\n"
            "Nested AGENTS.md files in subdirectories provide directory-specific instructions.\n\n"
            "Regenerate after changes: `haxaml export --agent codex`\n"
        ),
        "cursor": (
            "\n---\n\n"
            "## How to Use This File\n\n"
            "Cursor reads project rules from `.cursor/rules/` as `.mdc` files.\n"
            "This rule is set to `alwaysApply: true` — it applies to every conversation.\n\n"
            "Rule precedence: Team Rules → Project Rules → User Rules.\n\n"
            "Regenerate after changes: `haxaml export --agent cursor`\n"
        ),
        "gemini": (
            "\n---\n\n"
            "## How to Use This File\n\n"
            "Gemini CLI loads `GEMINI.md` context files from the workspace hierarchy.\n"
            "This file gives Gemini project facts, rules, current state, map guidance, and expected runs.\n\n"
            "Regenerate after changes: `haxaml export --agent gemini`\n"
        ),
        "generic": (
            "\n---\n\n"
            "## How to Use This File\n\n"
            "This is a universal governance file generated by Haxaml from FRAME.\n"
            "Paste it into any AI agent's system prompt or project instructions.\n\n"
            "Regenerate after changes: `haxaml export --agent generic`\n"
        ),
    }
    return tips.get(agent, tips["generic"])


def export_frame_to_markdown(project_dir: str, agent: str = "generic") -> str:
    """Export FRAME files to agent-specific markdown.

    Routes through the PromptRecipe pipeline:
      FrameModel.load() → build_recipe() → _render_recipe() → str

    Args:
        project_dir: Path to the project directory.
        agent: Target agent (claude, windsurf, copilot, codex, cursor, gemini, generic).

    Returns:
        Markdown string ready to write to file.
    """
    frame = FrameModel.load(project_dir)
    recipe = build_recipe(frame, agent)
    return _render_recipe(recipe)


def export_to_file(project_dir: str, agent: str = "generic",
                   output_path: Optional[str] = None,
                   override_native: bool = False,
                   overwrite_existing: bool = False) -> str:
    """Export FRAME to agent-specific markdown file.

    Args:
        project_dir: Path to the project directory.
        agent: Target agent.
        output_path: Override output path. If None, uses default for the agent.

    Returns:
        The path of the written file.
    """
    config = AGENT_CONFIGS[agent]
    content = export_frame_to_markdown(project_dir, agent)

    if output_path is None:
        filename = config.get("native_filename") if override_native else config["filename"]
        if not filename:
            filename = config["filename"]
        output_path = str(Path(project_dir) / filename)

    # Ensure parent directory exists
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    allow_replace = overwrite_existing or override_native
    if output.exists() and not allow_replace:
        existing = output.read_text(encoding="utf-8", errors="ignore")
        if GENERATED_MARKER not in existing:
            raise FileExistsError(
                f"Refusing to overwrite existing non-Haxaml file: {output}. "
                "Use override options if you explicitly want replacement."
            )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    return output_path


def list_agents() -> list[dict]:
    """List all supported agents with their output filenames."""
    return [
        {
            "name": name,
            "filename": cfg["filename"],
            "native_filename": cfg.get("native_filename"),
            "description": cfg["description"],
        }
        for name, cfg in AGENT_CONFIGS.items()
    ]
