"""Shared FRAME scaffold templates for CLI and MCP init flows."""

from pathlib import Path

from haxaml.paths import frame_path


FACTS_TEMPLATE = """\
# Project Facts (FRAME: F) — Generated by Haxaml
# Fill in ALL required fields before running `haxaml validate`.

identity:
  name: "my-project"
  version: "0.1.0"
  description: ""  # What is this project?

goal:
  purpose: ""  # Why does this project exist?
  scope: ""    # What is being built right now?
  out_of_scope: []

stack:
  language: ""    # REQUIRED: e.g. python, typescript, go
  backend: ""
  frontend: ""
  runtime: ""
  package_manager: ""

architecture:
  pattern: ""     # REQUIRED: e.g. layered, monolith, microservices
  reasoning: ""   # REQUIRED: why this pattern?
  boundaries: []

database:
  type: ""        # REQUIRED: e.g. postgres, mongodb, sqlite, none
  connection: ""  # REQUIRED: URI or 'none'
  migrations: ""

tools:
  testing: ""
  mcp: []
  ci: ""
  other: []

services: []

constraints:
  - ""  # At least one constraint required

success_criteria:
  - ""  # At least one criterion required

roles: []
features: []
unresolved: []
"""

RULES_TEMPLATE = """\
# Project Rules (FRAME: R) — Generated by Haxaml

governance:
  system: haxaml
  version: "0.1.0"

agent_profile:
  persona:
    role: "Deterministic implementation agent."
    tone:
      - "Direct and concise."
    constraints:
      - "Do not claim unimplemented benchmark proof."
  reasoning_policy:
    private_reasoning: "Keep private reasoning internal."
    public_rationale: "Provide concise rationale linked to code changes and checks."
    checklist:
      - "Summarize what changed."
      - "List tests or checks run."
      - "State remaining risks."
    prohibit_cot_transcript: true
  output_contract:
    required_sections:
      - "Summary"
      - "Changes"
      - "Verification"
      - "Risks"
  few_shot_examples: []
  example_policy:
    max_examples: 4
    max_input_chars: 260
    max_output_chars: 360
    max_total_chars: 2200
    derived_from_acts_max: 3
    ordering: explicit_then_derived
    fallback_when_empty: render_notice

before_task:
  read_first:
    - .haxaml/facts.yaml
    - .haxaml/rules.yaml
    - .haxaml/acts.yaml
  then_read:
    - .haxaml/expect.yaml
  check:
    - "Confirm the task matches project facts and current state."
    - "Read only source files relevant to the task."

boundaries:
  modules: {}
  rules:
    - "Stay within the task scope unless the user approves broader work."

while_coding:
  constraints:
    - "Keep changes small and testable."
  discipline:
    - "Run relevant tests before reporting completion."

after_task:
  report:
    - "What changed"
    - "What was tested"
    - "Risks or assumptions"
  update:
    - .haxaml/acts.yaml
  verify:
    - "Run haxaml validate when FRAME files change."

forbidden:
  - "Do not guess missing critical project facts."
  - "Do not edit unrelated modules without approval."

escalation:
  act_independently:
    - "Small scoped code or doc fixes within declared boundaries."
  ask_first:
    - "Architecture changes"
    - "New dependencies"
    - "Destructive operations"
"""

ACTS_TEMPLATE = """\
# Project Acts (FRAME: A) — Generated by Haxaml

current_phase: "Phase 0 — Setup"

active_task:
  name: "Fill in facts.yaml"
  description: "Complete all required fields in the project facts."

completed_tasks: []
blocked_tasks: []
decisions: []
unresolved_dependencies: []
runs: []

compaction:
  last_compacted: null
  total_runs_compacted: 0
  summary: "No runs yet."
"""

EXPECT_TEMPLATE = """\
# Project Expect (FRAME: E) — Generated by Haxaml

planning:
  goal: ""  # End state the project should reach.
  strategy: ""  # How runs move from foundations to the final goal.
  estimated_runs: 1
  project_size: small
  map_required: false
  map_reason: "Small project; .haxaml/rules.yaml boundaries are enough for now."

map_policy:
  small_project_max_runs: 5
  medium_project_max_runs: 12
  module_threshold: 10
  cross_impact_touch_threshold: 3
  cross_impact_run_threshold: 2
  dependency_fanout_threshold: 3
  impact_check_threshold: 3
  shared_integration_module_threshold: 2
  require_map_when:
    - "estimated_runs is greater than 12"
    - "the project has 10 or more modules"
    - "multiple runs touch three or more modules at once"
    - "external integrations or databases are shared across modules"
  agent_instruction: "When map_required is true or a run has uses_map=true, read .haxaml/map.yaml before touching source files."

phases:
  - name: "Phase 0 — Setup"
    status: active
    run_range: "1"
    target_runs: 1
    description: "Complete FRAME files and validate the project."
    done_when: ".haxaml/facts.yaml, .haxaml/rules.yaml, .haxaml/acts.yaml, and .haxaml/expect.yaml validate."

runbook:
  - run: 1
    phase: "Phase 0 — Setup"
    status: active
    goal: "Complete FRAME project setup."
    outcome: "All required FRAME files contain real project decisions and validate."
    depends_on: []
    touches:
      - facts
      - rules
      - acts
      - expect
    requires:
      - "Project goal"
      - "Stack decisions"
      - "Database or explicit no-database decision"
    uses_map: false
    verify:
      - "haxaml validate"
    done_when: "FRAME files validate and no blocking unresolved items remain."

upcoming:
  - task: "Complete facts.yaml"
    priority: critical
    phase: "Phase 0 — Setup"
    description: "Replace placeholders with real project decisions."

milestones:
  - name: "FRAME initialized"
    status: pending
    criteria: "haxaml validate passes."

open_questions: []
"""


def write_init_templates(project_dir: Path) -> None:
    """Write FRAME template files to .haxaml/ when they are missing."""
    templates = {
        "facts.yaml": FACTS_TEMPLATE,
        "rules.yaml": RULES_TEMPLATE,
        "acts.yaml": ACTS_TEMPLATE,
        "expect.yaml": EXPECT_TEMPLATE,
    }
    for filename, content in templates.items():
        path = frame_path(project_dir, filename)
        if not path.exists():
            path.write_text(content, encoding="utf-8")
