"""Shared FRAME scaffold templates for CLI and MCP init flows."""

from pathlib import Path

from haxaml.paths import frame_path
from haxaml.versioning import get_version


FACTS_TEMPLATE = """\
# Project Facts (FRAME: F) — Generated by Haxaml
# Fill in ALL required fields before running `haxaml validate`.

identity:
  name: ""
  version: ""
  description: ""

goal:
  purpose: ""
  scope: ""
  out_of_scope: []

stack:
  language: ""
  backend: ""
  frontend: ""
  runtime: ""
  package_manager: ""

architecture:
  pattern: ""
  reasoning: ""
  boundaries: []

database:
  type: ""
  connection: ""
  migrations: ""

tools:
  testing: ""
  mcp: []
  ci: ""
  other: []

services: []

constraints:
  - ""

success_criteria:
  - ""

roles: []
features: []
unresolved: []
"""

RULES_TEMPLATE = """\
# Project Rules (FRAME: R) — Generated by Haxaml

governance:
  system: haxaml
  version: "__HAXAML_VERSION__"

before_task:
  read_first:
    - .haxaml/facts.yaml
    - .haxaml/rules.yaml
    - .haxaml/acts.yaml
  then_read:
    - .haxaml/expect.yaml
  check:
    - "Confirm the task matches project facts and current state."
    - "Read only source files relevant to the task."

boundaries:
  modules: {}
  rules:
    - ""

while_coding:
  constraints:
    - ""
  discipline:
    - ""

after_task:
  report:
    - ""
  update:
    - ""
  verify:
    - ""

forbidden:
  - ""

escalation:
  act_independently:
    - ""
  ask_first:
    - ""

lifecycle:
  onboarding_full_reads: 5
  enforce_verify_before_record: true
  phases:
    - start
    - plan
    - act
    - verify
    - record
    - export

context_policy:
  default_pack: balanced
  max_items_per_section: 5
  max_chars_per_item: 240

clarification_policy:
  mode: risk_gated_soft_block
  min_task_chars: 16
  high_risk_keywords:
    - migrate
    - delete
    - auth
    - security
    - payment

verification_policy:
  require_checks:
    - understood_task
    - inspected_context
    - changed_right_files
    - risky_or_unrelated_touch
    - followed_rules
    - updated_journal
    - unresolved_logged
    - explained_changes
  allow_pass_with_risks: true

guidance_policy:
  task_type_hints: {}
  safer_path_templates: []
"""

ACTS_TEMPLATE = """\
# Project Acts (FRAME: A) — Generated by Haxaml

current_phase: ""

active_task:
  name: ""
  description: ""

completed_tasks: []
blocked_tasks: []
decisions: []
unresolved_dependencies: []
runs: []
sessions: []
verifications: []

compaction:
  last_compacted: null
  total_runs_compacted: 0
  summary: ""

context_compaction:
  sessions_started: 0
  full_reads_completed: 0
  default_pack: balanced
  last_pack_tokens: 0
"""

EXPECT_TEMPLATE = """\
# Project Expect (FRAME: E) — Generated by Haxaml

planning:
  goal: ""
  strategy: ""
  estimated_runs: 1
  project_size: small
  map_required: false
  map_reason: ""

map_policy:
  small_project_max_runs: 5
  medium_project_max_runs: 12
  module_threshold: 10
  cross_impact_touch_threshold: 3
  cross_impact_run_threshold: 2
  dependency_fanout_threshold: 3
  impact_check_threshold: 3
  shared_integration_module_threshold: 2
  require_map_when:
    - ""
  agent_instruction: ""

phases:
  - name: ""
    status: active
    run_range: ""
    target_runs: 1
    description: ""
    done_when: ""

runbook:
  - run: 1
    phase: ""
    status: active
    goal: ""
    outcome: ""
    depends_on: []
    touches:
      - ""
    requires:
      - ""
    uses_map: false
    verify:
      - ""
    done_when: ""

upcoming:
  - task: ""
    priority: critical
    phase: ""
    description: ""

milestones:
  - name: ""
    status: pending
    criteria: ""

open_questions: []
"""


def write_init_templates(project_dir: Path) -> None:
    """Write FRAME template files to .haxaml/ when they are missing."""
    version = get_version()
    templates = {
        "facts.yaml": FACTS_TEMPLATE,
        "rules.yaml": RULES_TEMPLATE.replace("__HAXAML_VERSION__", version),
        "acts.yaml": ACTS_TEMPLATE,
        "expect.yaml": EXPECT_TEMPLATE,
    }
    for filename, content in templates.items():
        path = frame_path(project_dir, filename)
        if not path.exists():
            path.write_text(content, encoding="utf-8")
