"""Shared FRAME scaffold templates for CLI and MCP init flows."""

from pathlib import Path

import yaml

from haxaml.paths import frame_path
from haxaml.versioning import get_version


FACTS_TEMPLATE = """\
# Project Facts (FRAME: F) — Generated by Haxaml
# Fill in ALL required fields before running `haxaml validate`.

identity:
  name: ""
  version: ""
  description: ""

goal:
  purpose: ""
  scope: ""
  out_of_scope: []

stack:
  language: ""
  backend: ""
  frontend: ""
  runtime: ""
  package_manager: ""

architecture:
  pattern: ""
  reasoning: ""
  boundaries: []

database:
  type: ""
  connection: ""
  migrations: ""

tools:
  testing: ""
  mcp: []
  ci: ""
  other: []

services: []

constraints:
  - "Keep implementation changes scoped to the active task."

success_criteria:
  - "Task outcome is verified and recorded before claiming completion."

roles: []
features: []
unresolved: []
"""

RULES_TEMPLATE = """\
# Project Rules (FRAME: R) — Generated by Haxaml

governance:
  system: haxaml
  version: "__HAXAML_VERSION__"

before_task:
  read_first:
    - .haxaml/facts.yaml
    - .haxaml/rules.yaml
    - .haxaml/acts.yaml
  then_read:
    - .haxaml/expect.yaml
  check:
    - "Confirm the task matches project facts and current state."
    - "Read only source files relevant to the task."

boundaries:
  modules: {}
  rules:
    - "Edit only files relevant to the active task scope."

while_coding:
  constraints:
    - "Keep changes minimal and reversible where possible."
  discipline:
    - "Use short, accurate commit messages in plain language."
    - "Do not use commit prefixes like fix:, feat:, refactor:, chore:, or docs:."
    - "Run tests or validation for touched behavior."

after_task:
  report:
    - "Summarize what changed, why, and known risks."
  update:
    - ".haxaml/acts.yaml"
  verify:
    - "Run relevant tests or validation checks."

forbidden:
  - "Do not claim success without verification evidence."

escalation:
  act_independently:
    - "Small scoped implementation and test fixes."
  ask_first:
    - "Architecture changes, destructive data operations, or production-risk actions."

lifecycle:
  onboarding_full_reads: 5
  enforce_verify_before_record: true
  phases:
    - start
    - plan
    - act
    - verify
    - record
    - export

context_policy:
  default_pack: balanced
  max_items_per_section: 5
  max_chars_per_item: 240

clarification_policy:
  mode: risk_gated_soft_block
  min_task_chars: 16
  high_risk_keywords:
    - migrate
    - delete
    - auth
    - security
    - payment

verification_policy:
  require_checks:
    - understood_task
    - inspected_context
    - changed_right_files
    - risky_or_unrelated_touch
    - followed_rules
    - updated_journal
    - unresolved_logged
    - explained_changes
  allow_pass_with_risks: true

guidance_policy:
  task_type_hints: {}
  safer_path_templates: []
"""

ACTS_TEMPLATE = """\
# Project Acts (FRAME: A) — Generated by Haxaml

current_phase: ""

active_task:
  name: ""
  description: ""

completed_tasks: []
blocked_tasks: []
decisions: []
unresolved_dependencies: []
runs: []
sessions: []
verifications: []

compaction:
  last_compacted: null
  total_runs_compacted: 0
  summary: ""

context_compaction:
  sessions_started: 0
  full_reads_completed: 0
  default_pack: balanced
  last_pack_tokens: 0
"""

EXPECT_TEMPLATE = """\
# Project Expect (FRAME: E) — Generated by Haxaml

planning:
  goal: "Complete scoped tasks with governed verification."
  strategy: "Iterative small runs with validation before record."
  estimated_runs: 1
  project_size: small
  map_required: false
  map_reason: "Map is optional by default for a new scaffold."

map_policy:
  small_project_max_runs: 5
  medium_project_max_runs: 12
  module_threshold: 10
  cross_impact_touch_threshold: 3
  cross_impact_run_threshold: 2
  dependency_fanout_threshold: 3
  impact_check_threshold: 3
  shared_integration_module_threshold: 2
  require_map_when:
    - "Module count exceeds policy threshold."
  agent_instruction: "Read map.yaml when map_required is true or when task impact crosses module boundaries."

phases:
  - name: "Phase 1"
    status: active
    run_range: "1-1"
    target_runs: 1
    description: "Bootstrap and execute the first governed task."
    done_when: "A scoped task is verified and recorded."

runbook:
  - run: 1
    phase: "Phase 1"
    status: active
    goal: "Execute one scoped task safely."
    outcome: "Task progress is verified and recorded."
    depends_on: []
    touches:
      - "scoped files only"
    requires:
      - "Clear task statement"
    uses_map: false
    verify:
      - "Run tests or validation relevant to touched behavior."
    done_when: "Verification passes and session is recorded."

upcoming:
  - task: "Define the next scoped task"
    priority: critical
    phase: "Phase 1"
    description: "Prepare context, execute, verify, and record."

milestones:
  - name: "First governed run complete"
    status: pending
    criteria: "At least one run is verified and recorded without unresolved blockers."

open_questions: []
"""


def write_init_templates(project_dir: Path) -> None:
    """Write FRAME template files to .haxaml/ when they are missing."""
    version = get_version()
    templates = {
        "facts.yaml": FACTS_TEMPLATE,
        "rules.yaml": RULES_TEMPLATE.replace("__HAXAML_VERSION__", version),
        "acts.yaml": ACTS_TEMPLATE,
        "expect.yaml": EXPECT_TEMPLATE,
    }
    for filename, content in templates.items():
        path = frame_path(project_dir, filename)
        if not path.exists():
            path.write_text(content, encoding="utf-8")


def sync_rules_governance_version(project_dir: Path) -> dict:
    """Sync governance.version in .haxaml/rules.yaml to the current Haxaml version."""
    rules_path = frame_path(project_dir, "rules.yaml")
    target_version = get_version()
    if not rules_path.exists():
        return {
            "updated": False,
            "path": str(rules_path),
            "reason": "missing",
            "from": "",
            "to": target_version,
        }

    try:
        data = yaml.safe_load(rules_path.read_text(encoding="utf-8")) or {}
    except Exception as exc:  # pragma: no cover - defensive parse guard
        return {
            "updated": False,
            "path": str(rules_path),
            "reason": "parse_error",
            "from": "",
            "to": target_version,
            "error": str(exc),
        }

    if not isinstance(data, dict):
        return {
            "updated": False,
            "path": str(rules_path),
            "reason": "invalid_yaml_root",
            "from": "",
            "to": target_version,
        }

    governance = data.get("governance")
    if not isinstance(governance, dict):
        governance = {}
        data["governance"] = governance

    current_version = str(governance.get("version", "")).strip()
    if current_version == target_version:
        return {
            "updated": False,
            "path": str(rules_path),
            "reason": "already_current",
            "from": current_version,
            "to": target_version,
        }

    governance["system"] = str(governance.get("system", "")).strip() or "haxaml"
    governance["version"] = target_version
    rules_path.write_text(yaml.dump(data, default_flow_style=False, sort_keys=False), encoding="utf-8")
    return {
        "updated": True,
        "path": str(rules_path),
        "reason": "updated",
        "from": current_version,
        "to": target_version,
    }
